# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawConferenceClient, RawConferenceClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ConferenceClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawConferenceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawConferenceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawConferenceClient
        """
        return self._raw_client

    def kick_member(
        self,
        auth_id: str,
        conference_name: str,
        member_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Remove a specific participant from a conference call.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        conference_name : str

        member_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Member kicked

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.conference.kick_member(
            auth_id="MA_XXXXXX",
            conference_name="conference_name",
            member_id="member_id",
        )
        """
        _response = self._raw_client.kick_member(auth_id, conference_name, member_id, request_options=request_options)
        return _response.data

    def hangup_member(
        self,
        auth_id: str,
        conference_name: str,
        member_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Disconnect a specific member from a conference.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        conference_name : str

        member_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.conference.hangup_member(
            auth_id="MA_XXXXXX",
            conference_name="conference_name",
            member_id="member_id",
        )
        """
        _response = self._raw_client.hangup_member(auth_id, conference_name, member_id, request_options=request_options)
        return _response.data

    def play_audio_member(
        self,
        auth_id: str,
        conference_name: str,
        member_id: str,
        *,
        url: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Play an audio file to a specific conference member.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        conference_name : str

        member_id : str

        url : str
            URL of the audio file to play

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.conference.play_audio_member(
            auth_id="MA_XXXXXX",
            conference_name="conference_name",
            member_id="member_id",
            url="https://example.com/audio.mp3",
        )
        """
        _response = self._raw_client.play_audio_member(
            auth_id, conference_name, member_id, url=url, request_options=request_options
        )
        return _response.data

    def stop_audio_member(
        self,
        auth_id: str,
        conference_name: str,
        member_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Stop audio playback for a specific conference member.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        conference_name : str

        member_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.conference.stop_audio_member(
            auth_id="MA_XXXXXX",
            conference_name="conference_name",
            member_id="member_id",
        )
        """
        _response = self._raw_client.stop_audio_member(
            auth_id, conference_name, member_id, request_options=request_options
        )
        return _response.data

    def deaf_member(
        self,
        auth_id: str,
        conference_name: str,
        member_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Prevent a conference member from hearing other participants.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        conference_name : str

        member_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.conference.deaf_member(
            auth_id="MA_XXXXXX",
            conference_name="conference_name",
            member_id="member_id",
        )
        """
        _response = self._raw_client.deaf_member(auth_id, conference_name, member_id, request_options=request_options)
        return _response.data

    def undeaf_member(
        self,
        auth_id: str,
        conference_name: str,
        member_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Restore a conference member's ability to hear other participants.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        conference_name : str

        member_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.conference.undeaf_member(
            auth_id="MA_XXXXXX",
            conference_name="conference_name",
            member_id="member_id",
        )
        """
        _response = self._raw_client.undeaf_member(auth_id, conference_name, member_id, request_options=request_options)
        return _response.data


class AsyncConferenceClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawConferenceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawConferenceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawConferenceClient
        """
        return self._raw_client

    async def kick_member(
        self,
        auth_id: str,
        conference_name: str,
        member_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Remove a specific participant from a conference call.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        conference_name : str

        member_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Member kicked

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.conference.kick_member(
                auth_id="MA_XXXXXX",
                conference_name="conference_name",
                member_id="member_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.kick_member(
            auth_id, conference_name, member_id, request_options=request_options
        )
        return _response.data

    async def hangup_member(
        self,
        auth_id: str,
        conference_name: str,
        member_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Disconnect a specific member from a conference.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        conference_name : str

        member_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.conference.hangup_member(
                auth_id="MA_XXXXXX",
                conference_name="conference_name",
                member_id="member_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.hangup_member(
            auth_id, conference_name, member_id, request_options=request_options
        )
        return _response.data

    async def play_audio_member(
        self,
        auth_id: str,
        conference_name: str,
        member_id: str,
        *,
        url: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Play an audio file to a specific conference member.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        conference_name : str

        member_id : str

        url : str
            URL of the audio file to play

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.conference.play_audio_member(
                auth_id="MA_XXXXXX",
                conference_name="conference_name",
                member_id="member_id",
                url="https://example.com/audio.mp3",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.play_audio_member(
            auth_id, conference_name, member_id, url=url, request_options=request_options
        )
        return _response.data

    async def stop_audio_member(
        self,
        auth_id: str,
        conference_name: str,
        member_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Stop audio playback for a specific conference member.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        conference_name : str

        member_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.conference.stop_audio_member(
                auth_id="MA_XXXXXX",
                conference_name="conference_name",
                member_id="member_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.stop_audio_member(
            auth_id, conference_name, member_id, request_options=request_options
        )
        return _response.data

    async def deaf_member(
        self,
        auth_id: str,
        conference_name: str,
        member_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Prevent a conference member from hearing other participants.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        conference_name : str

        member_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.conference.deaf_member(
                auth_id="MA_XXXXXX",
                conference_name="conference_name",
                member_id="member_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.deaf_member(
            auth_id, conference_name, member_id, request_options=request_options
        )
        return _response.data

    async def undeaf_member(
        self,
        auth_id: str,
        conference_name: str,
        member_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Restore a conference member's ability to hear other participants.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        conference_name : str

        member_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.conference.undeaf_member(
                auth_id="MA_XXXXXX",
                conference_name="conference_name",
                member_id="member_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.undeaf_member(
            auth_id, conference_name, member_id, request_options=request_options
        )
        return _response.data
