# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawCallsClient, RawCallsClient
from .types.make_call_response import MakeCallResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CallsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCallsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCallsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCallsClient
        """
        return self._raw_client

    def make_call(
        self,
        auth_id: str,
        *,
        from_: str,
        to: str,
        answer_url: str,
        answer_method: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MakeCallResponse:
        """
        Initiate an outbound call to a PSTN number or SIP endpoint.
        Use `<` to separate multiple destinations (max 1000).

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        from_ : str

        to : str

        answer_url : str

        answer_method : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MakeCallResponse
            Call initiated

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.calls.make_call(
            auth_id="MA_XXXXXX",
            from_="14155551234",
            to="+919876543210",
            answer_url="https://example.com/answer",
            answer_method="POST",
        )
        """
        _response = self._raw_client.make_call(
            auth_id,
            from_=from_,
            to=to,
            answer_url=answer_url,
            answer_method=answer_method,
            request_options=request_options,
        )
        return _response.data


class AsyncCallsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCallsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCallsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCallsClient
        """
        return self._raw_client

    async def make_call(
        self,
        auth_id: str,
        *,
        from_: str,
        to: str,
        answer_url: str,
        answer_method: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MakeCallResponse:
        """
        Initiate an outbound call to a PSTN number or SIP endpoint.
        Use `<` to separate multiple destinations (max 1000).

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        from_ : str

        to : str

        answer_url : str

        answer_method : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MakeCallResponse
            Call initiated

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.calls.make_call(
                auth_id="MA_XXXXXX",
                from_="14155551234",
                to="+919876543210",
                answer_url="https://example.com/answer",
                answer_method="POST",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.make_call(
            auth_id,
            from_=from_,
            to=to,
            answer_url=answer_url,
            answer_method=answer_method,
            request_options=request_options,
        )
        return _response.data
