# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawTrunksClient, RawTrunksClient
from .types.create_trunk_request_webhook_method import CreateTrunkRequestWebhookMethod
from .types.create_trunk_response import CreateTrunkResponse
from .types.list_trunks_response import ListTrunksResponse
from .types.retrieve_trunk_response import RetrieveTrunkResponse
from .types.update_trunk_request_webhook_method import UpdateTrunkRequestWebhookMethod
from .types.update_trunk_response import UpdateTrunkResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class TrunksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawTrunksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawTrunksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawTrunksClient
        """
        return self._raw_client

    def list_trunks(
        self, auth_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListTrunksResponse:
        """
        Retrieve all SIP trunks configured on the account.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListTrunksResponse
            List of trunks

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.trunks.list_trunks(
            auth_id="MA_XXXXXX",
        )
        """
        _response = self._raw_client.list_trunks(auth_id, request_options=request_options)
        return _response.data

    def create_trunk(
        self,
        auth_id: str,
        *,
        name: str,
        trunk_type: str,
        max_concurrent_calls: int,
        webhook_url: typing.Optional[str] = OMIT,
        webhook_method: typing.Optional[CreateTrunkRequestWebhookMethod] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateTrunkResponse:
        """
        Create a new SIP trunk for inbound or outbound calling.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        name : str

        trunk_type : str

        max_concurrent_calls : int

        webhook_url : typing.Optional[str]
            HTTPS URL to receive real-time call-event webhooks (`CallInitiated`
            and `Hangup`) for this trunk. Max 500 characters; private, localhost,
            and cloud-metadata IPs are blocked. See [Trunk Webhooks](/trunks/webhook).

        webhook_method : typing.Optional[CreateTrunkRequestWebhookMethod]
            HTTP method for the webhook callback. Defaults to `POST`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateTrunkResponse
            Success

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.trunks.create_trunk(
            auth_id="MA_XXXXXX",
            name="My Outbound Trunk",
            trunk_type="OUTBOUND",
            max_concurrent_calls=10,
            webhook_url="https://your-app.example.com/trunk-webhook",
            webhook_method="POST",
        )
        """
        _response = self._raw_client.create_trunk(
            auth_id,
            name=name,
            trunk_type=trunk_type,
            max_concurrent_calls=max_concurrent_calls,
            webhook_url=webhook_url,
            webhook_method=webhook_method,
            request_options=request_options,
        )
        return _response.data

    def retrieve_trunk(
        self, auth_id: str, trunk_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RetrieveTrunkResponse:
        """
        Get details of a specific SIP trunk.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        trunk_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetrieveTrunkResponse
            Trunk details

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.trunks.retrieve_trunk(
            auth_id="MA_XXXXXX",
            trunk_id="trunk_XXXXXX",
        )
        """
        _response = self._raw_client.retrieve_trunk(auth_id, trunk_id, request_options=request_options)
        return _response.data

    def update_trunk(
        self,
        auth_id: str,
        trunk_id: str,
        *,
        name: str,
        max_concurrent_calls: int,
        enabled: bool,
        webhook_url: typing.Optional[str] = OMIT,
        webhook_method: typing.Optional[UpdateTrunkRequestWebhookMethod] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateTrunkResponse:
        """
        Update a SIP trunk's name, configuration, or status.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        trunk_id : str

        name : str

        max_concurrent_calls : int

        enabled : bool

        webhook_url : typing.Optional[str]
            HTTPS URL for real-time call-event webhooks (`CallInitiated`, `Hangup`). See [Trunk Webhooks](/trunks/webhook).

        webhook_method : typing.Optional[UpdateTrunkRequestWebhookMethod]
            HTTP method for the webhook callback. Defaults to `POST`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateTrunkResponse
            Trunk updated

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.trunks.update_trunk(
            auth_id="MA_XXXXXX",
            trunk_id="trunk_id",
            name="name",
            max_concurrent_calls=1,
            enabled=True,
        )
        """
        _response = self._raw_client.update_trunk(
            auth_id,
            trunk_id,
            name=name,
            max_concurrent_calls=max_concurrent_calls,
            enabled=enabled,
            webhook_url=webhook_url,
            webhook_method=webhook_method,
            request_options=request_options,
        )
        return _response.data

    def delete_trunk(
        self, auth_id: str, trunk_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[str]:
        """
        Permanently delete a SIP trunk.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        trunk_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[str]
            Success

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.trunks.delete_trunk(
            auth_id="MA_XXXXXX",
            trunk_id="trunk_id",
        )
        """
        _response = self._raw_client.delete_trunk(auth_id, trunk_id, request_options=request_options)
        return _response.data


class AsyncTrunksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawTrunksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawTrunksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawTrunksClient
        """
        return self._raw_client

    async def list_trunks(
        self, auth_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListTrunksResponse:
        """
        Retrieve all SIP trunks configured on the account.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListTrunksResponse
            List of trunks

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.trunks.list_trunks(
                auth_id="MA_XXXXXX",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_trunks(auth_id, request_options=request_options)
        return _response.data

    async def create_trunk(
        self,
        auth_id: str,
        *,
        name: str,
        trunk_type: str,
        max_concurrent_calls: int,
        webhook_url: typing.Optional[str] = OMIT,
        webhook_method: typing.Optional[CreateTrunkRequestWebhookMethod] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateTrunkResponse:
        """
        Create a new SIP trunk for inbound or outbound calling.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        name : str

        trunk_type : str

        max_concurrent_calls : int

        webhook_url : typing.Optional[str]
            HTTPS URL to receive real-time call-event webhooks (`CallInitiated`
            and `Hangup`) for this trunk. Max 500 characters; private, localhost,
            and cloud-metadata IPs are blocked. See [Trunk Webhooks](/trunks/webhook).

        webhook_method : typing.Optional[CreateTrunkRequestWebhookMethod]
            HTTP method for the webhook callback. Defaults to `POST`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateTrunkResponse
            Success

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.trunks.create_trunk(
                auth_id="MA_XXXXXX",
                name="My Outbound Trunk",
                trunk_type="OUTBOUND",
                max_concurrent_calls=10,
                webhook_url="https://your-app.example.com/trunk-webhook",
                webhook_method="POST",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_trunk(
            auth_id,
            name=name,
            trunk_type=trunk_type,
            max_concurrent_calls=max_concurrent_calls,
            webhook_url=webhook_url,
            webhook_method=webhook_method,
            request_options=request_options,
        )
        return _response.data

    async def retrieve_trunk(
        self, auth_id: str, trunk_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RetrieveTrunkResponse:
        """
        Get details of a specific SIP trunk.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        trunk_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetrieveTrunkResponse
            Trunk details

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.trunks.retrieve_trunk(
                auth_id="MA_XXXXXX",
                trunk_id="trunk_XXXXXX",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve_trunk(auth_id, trunk_id, request_options=request_options)
        return _response.data

    async def update_trunk(
        self,
        auth_id: str,
        trunk_id: str,
        *,
        name: str,
        max_concurrent_calls: int,
        enabled: bool,
        webhook_url: typing.Optional[str] = OMIT,
        webhook_method: typing.Optional[UpdateTrunkRequestWebhookMethod] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateTrunkResponse:
        """
        Update a SIP trunk's name, configuration, or status.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        trunk_id : str

        name : str

        max_concurrent_calls : int

        enabled : bool

        webhook_url : typing.Optional[str]
            HTTPS URL for real-time call-event webhooks (`CallInitiated`, `Hangup`). See [Trunk Webhooks](/trunks/webhook).

        webhook_method : typing.Optional[UpdateTrunkRequestWebhookMethod]
            HTTP method for the webhook callback. Defaults to `POST`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateTrunkResponse
            Trunk updated

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.trunks.update_trunk(
                auth_id="MA_XXXXXX",
                trunk_id="trunk_id",
                name="name",
                max_concurrent_calls=1,
                enabled=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_trunk(
            auth_id,
            trunk_id,
            name=name,
            max_concurrent_calls=max_concurrent_calls,
            enabled=enabled,
            webhook_url=webhook_url,
            webhook_method=webhook_method,
            request_options=request_options,
        )
        return _response.data

    async def delete_trunk(
        self, auth_id: str, trunk_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[str]:
        """
        Permanently delete a SIP trunk.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        trunk_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[str]
            Success

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.trunks.delete_trunk(
                auth_id="MA_XXXXXX",
                trunk_id="trunk_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_trunk(auth_id, trunk_id, request_options=request_options)
        return _response.data
