# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from .types.create_trunk_response import CreateTrunkResponse
from .types.list_trunks_response import ListTrunksResponse
from .types.retrieve_trunk_response import RetrieveTrunkResponse
from .types.update_trunk_response import UpdateTrunkResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawTrunksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_trunks(
        self, auth_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ListTrunksResponse]:
        """
        Retrieve all SIP trunks configured on the account.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListTrunksResponse]
            List of trunks
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/trunks",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListTrunksResponse,
                    parse_obj_as(
                        type_=ListTrunksResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_trunk(
        self,
        auth_id: str,
        *,
        name: str,
        trunk_type: str,
        max_concurrent_calls: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateTrunkResponse]:
        """
        Create a new SIP trunk for inbound or outbound calling.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        name : str

        trunk_type : str

        max_concurrent_calls : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateTrunkResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/trunks",
            method="POST",
            json={
                "name": name,
                "trunk_type": trunk_type,
                "max_concurrent_calls": max_concurrent_calls,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateTrunkResponse,
                    parse_obj_as(
                        type_=CreateTrunkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def retrieve_trunk(
        self, auth_id: str, trunk_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[RetrieveTrunkResponse]:
        """
        Get details of a specific SIP trunk.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        trunk_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[RetrieveTrunkResponse]
            Trunk details
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/trunks/{encode_path_param(trunk_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RetrieveTrunkResponse,
                    parse_obj_as(
                        type_=RetrieveTrunkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_trunk(
        self,
        auth_id: str,
        trunk_id: str,
        *,
        name: str,
        max_concurrent_calls: int,
        enabled: bool,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[UpdateTrunkResponse]:
        """
        Update a SIP trunk's name, configuration, or status.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        trunk_id : str

        name : str

        max_concurrent_calls : int

        enabled : bool

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[UpdateTrunkResponse]
            Trunk updated
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/trunks/{encode_path_param(trunk_id)}",
            method="PUT",
            json={
                "name": name,
                "max_concurrent_calls": max_concurrent_calls,
                "enabled": enabled,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdateTrunkResponse,
                    parse_obj_as(
                        type_=UpdateTrunkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_trunk(
        self, auth_id: str, trunk_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Optional[str]]:
        """
        Permanently delete a SIP trunk.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        trunk_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Optional[str]]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/trunks/{encode_path_param(trunk_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[str],
                    parse_obj_as(
                        type_=typing.Optional[str],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawTrunksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_trunks(
        self, auth_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ListTrunksResponse]:
        """
        Retrieve all SIP trunks configured on the account.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListTrunksResponse]
            List of trunks
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/trunks",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListTrunksResponse,
                    parse_obj_as(
                        type_=ListTrunksResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_trunk(
        self,
        auth_id: str,
        *,
        name: str,
        trunk_type: str,
        max_concurrent_calls: int,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateTrunkResponse]:
        """
        Create a new SIP trunk for inbound or outbound calling.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        name : str

        trunk_type : str

        max_concurrent_calls : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateTrunkResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/trunks",
            method="POST",
            json={
                "name": name,
                "trunk_type": trunk_type,
                "max_concurrent_calls": max_concurrent_calls,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateTrunkResponse,
                    parse_obj_as(
                        type_=CreateTrunkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def retrieve_trunk(
        self, auth_id: str, trunk_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[RetrieveTrunkResponse]:
        """
        Get details of a specific SIP trunk.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        trunk_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[RetrieveTrunkResponse]
            Trunk details
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/trunks/{encode_path_param(trunk_id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    RetrieveTrunkResponse,
                    parse_obj_as(
                        type_=RetrieveTrunkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_trunk(
        self,
        auth_id: str,
        trunk_id: str,
        *,
        name: str,
        max_concurrent_calls: int,
        enabled: bool,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[UpdateTrunkResponse]:
        """
        Update a SIP trunk's name, configuration, or status.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        trunk_id : str

        name : str

        max_concurrent_calls : int

        enabled : bool

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[UpdateTrunkResponse]
            Trunk updated
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/trunks/{encode_path_param(trunk_id)}",
            method="PUT",
            json={
                "name": name,
                "max_concurrent_calls": max_concurrent_calls,
                "enabled": enabled,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdateTrunkResponse,
                    parse_obj_as(
                        type_=UpdateTrunkResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_trunk(
        self, auth_id: str, trunk_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Optional[str]]:
        """
        Permanently delete a SIP trunk.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        trunk_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Optional[str]]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/trunks/{encode_path_param(trunk_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[str],
                    parse_obj_as(
                        type_=typing.Optional[str],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
