# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .retrieve_account_response_features import RetrieveAccountResponseFeatures
from .retrieve_account_response_pricing_tier import RetrieveAccountResponsePricingTier


class RetrieveAccountResponse(UniversalBaseModel):
    type: str
    id: str
    api_id: str
    name: str
    email: str
    phone: str
    description: str
    auth_id: str
    auth_secret: str
    auth_token_expire_time: typing.Optional[typing.Any] = None
    country: str
    timezone: str
    city: str
    state: str
    address: str
    zip_code: str
    company: str
    account_type: str
    postpaid: bool
    auto_recharge: bool
    auto_recharge_config: typing.Optional[typing.Any] = None
    enabled: bool
    carrier_type: typing.Optional[typing.Any] = None
    customer_type: typing.Optional[typing.Any] = None
    credit_limit: int
    cps_limit: int
    concurrent_calls_limit: int
    base_cps_limit: int
    base_concurrent_calls_limit: int
    purchased_cps: int
    purchased_concurrent_calls: int
    risk_rating: int
    risk_status: typing.Optional[typing.Any] = None
    features: RetrieveAccountResponseFeatures
    ip_auth_enabled: bool
    ip_whitelist_rules: typing.Dict[str, typing.Any]
    allow_aws_ips: bool
    role: str
    is_active: bool
    is_verified: bool
    is_trial_account: bool
    created_at: str
    updated_at: str
    last_login: str
    pricing_tier_id: str
    pricing_tier: RetrieveAccountResponsePricingTier

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.forbid
