# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class GetCdrResponseData(UniversalBaseModel):
    account_id: str
    answer_time: str
    billsec: int
    bridge_uuid: str
    call_direction: str
    caller_id_name: str
    caller_id_number: str
    campaign_id: typing.Optional[typing.Any] = None
    carrier_ip: typing.Optional[typing.Any] = None
    codec: str
    context: str
    cost: float
    created_at: str
    currency: str
    customer_endpoint: typing.Optional[typing.Any] = None
    destination_number: str
    duration: int
    end_time: str
    failure_code: typing.Optional[typing.Any] = None
    failure_reason: typing.Optional[typing.Any] = None
    hangup_cause: str
    hangup_cause_code: int
    hangup_cause_name: str
    hangup_disposition: str
    hangup_source: str
    id: int
    jitter: float
    mos: float
    network_addr: str
    origination_region: str
    packet_loss: int
    progress_time: str
    region: str
    ring_time: int
    sip_call_id: str
    sip_user_agent: str
    start_time: str
    streaming_cost: int
    terminated_to: typing.Optional[typing.Any] = None
    total_cost: float
    trunk_id: typing.Optional[typing.Any] = None
    updated_at: str
    uuid_: typing_extensions.Annotated[str, FieldMetadata(alias="uuid"), pydantic.Field(alias="uuid")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.forbid
