# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawConferencesClient, RawConferencesClient
from .types.list_conferences_response import ListConferencesResponse


class ConferencesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawConferencesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawConferencesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawConferencesClient
        """
        return self._raw_client

    def list_conferences(
        self, auth_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListConferencesResponse:
        """
        Retrieve all active conference rooms on the account.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListConferencesResponse
            List of conferences

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.conferences.list_conferences(
            auth_id="MA_XXXXXX",
        )
        """
        _response = self._raw_client.list_conferences(auth_id, request_options=request_options)
        return _response.data

    def delete_all_conferences(self, auth_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Terminate all active conference rooms.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.conferences.delete_all_conferences(
            auth_id="MA_XXXXXX",
        )
        """
        _response = self._raw_client.delete_all_conferences(auth_id, request_options=request_options)
        return _response.data

    def get_conference(
        self, auth_id: str, conference_name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Get details and member list of a specific conference room.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        conference_name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Conference details

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.conferences.get_conference(
            auth_id="MA_XXXXXX",
            conference_name="My Conf Room",
        )
        """
        _response = self._raw_client.get_conference(auth_id, conference_name, request_options=request_options)
        return _response.data

    def delete_conference(
        self, auth_id: str, conference_name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Terminate a specific conference room and disconnect all members.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        conference_name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.conferences.delete_conference(
            auth_id="MA_XXXXXX",
            conference_name="conference_name",
        )
        """
        _response = self._raw_client.delete_conference(auth_id, conference_name, request_options=request_options)
        return _response.data


class AsyncConferencesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawConferencesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawConferencesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawConferencesClient
        """
        return self._raw_client

    async def list_conferences(
        self, auth_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListConferencesResponse:
        """
        Retrieve all active conference rooms on the account.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListConferencesResponse
            List of conferences

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.conferences.list_conferences(
                auth_id="MA_XXXXXX",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_conferences(auth_id, request_options=request_options)
        return _response.data

    async def delete_all_conferences(
        self, auth_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Terminate all active conference rooms.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.conferences.delete_all_conferences(
                auth_id="MA_XXXXXX",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_all_conferences(auth_id, request_options=request_options)
        return _response.data

    async def get_conference(
        self, auth_id: str, conference_name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Get details and member list of a specific conference room.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        conference_name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Conference details

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.conferences.get_conference(
                auth_id="MA_XXXXXX",
                conference_name="My Conf Room",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_conference(auth_id, conference_name, request_options=request_options)
        return _response.data

    async def delete_conference(
        self, auth_id: str, conference_name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Terminate a specific conference room and disconnect all members.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        conference_name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.conferences.delete_conference(
                auth_id="MA_XXXXXX",
                conference_name="conference_name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_conference(auth_id, conference_name, request_options=request_options)
        return _response.data
