# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_credential_response import CreateCredentialResponse
    from .list_credentials_response import ListCredentialsResponse
    from .list_credentials_response_meta import ListCredentialsResponseMeta
    from .list_credentials_response_objects_item import ListCredentialsResponseObjectsItem
    from .update_credential_response import UpdateCredentialResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CreateCredentialResponse": ".create_credential_response",
    "ListCredentialsResponse": ".list_credentials_response",
    "ListCredentialsResponseMeta": ".list_credentials_response_meta",
    "ListCredentialsResponseObjectsItem": ".list_credentials_response_objects_item",
    "UpdateCredentialResponse": ".update_credential_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateCredentialResponse",
    "ListCredentialsResponse",
    "ListCredentialsResponseMeta",
    "ListCredentialsResponseObjectsItem",
    "UpdateCredentialResponse",
]
