# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from .types.create_ip_acl_response import CreateIpAclResponse
from .types.list_ip_acls_response import ListIpAclsResponse
from .types.update_ip_acl_response import UpdateIpAclResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawIpAccessControlListClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create_ip_acl(
        self, auth_id: str, *, name: str, ip_address: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[CreateIpAclResponse]:
        """
        Add an IP access control rule to restrict SIP trunk access.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        name : str

        ip_address : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateIpAclResponse]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/ip-acl",
            method="POST",
            json={
                "name": name,
                "ip_address": ip_address,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateIpAclResponse,
                    parse_obj_as(
                        type_=CreateIpAclResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_ip_acls(
        self, auth_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ListIpAclsResponse]:
        """
        Retrieve all IP access control rules on the account.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListIpAclsResponse]
            List of IP ACLs
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/trunks/ip-acl",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListIpAclsResponse,
                    parse_obj_as(
                        type_=ListIpAclsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_ip_acl(
        self,
        auth_id: str,
        ip_acl_id: str,
        *,
        name: str,
        ip_address: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[UpdateIpAclResponse]:
        """
        Update an existing IP access control rule.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        ip_acl_id : str

        name : str

        ip_address : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[UpdateIpAclResponse]
            IP ACL updated
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/ip-acl/{encode_path_param(ip_acl_id)}",
            method="PUT",
            json={
                "name": name,
                "ip_address": ip_address,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdateIpAclResponse,
                    parse_obj_as(
                        type_=UpdateIpAclResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_ip_acl(
        self, auth_id: str, ip_acl_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Optional[str]]:
        """
        Remove an IP access control rule.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        ip_acl_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Optional[str]]
            Success
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/ip-acl/{encode_path_param(ip_acl_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[str],
                    parse_obj_as(
                        type_=typing.Optional[str],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawIpAccessControlListClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create_ip_acl(
        self, auth_id: str, *, name: str, ip_address: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CreateIpAclResponse]:
        """
        Add an IP access control rule to restrict SIP trunk access.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        name : str

        ip_address : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateIpAclResponse]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/ip-acl",
            method="POST",
            json={
                "name": name,
                "ip_address": ip_address,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateIpAclResponse,
                    parse_obj_as(
                        type_=CreateIpAclResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_ip_acls(
        self, auth_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ListIpAclsResponse]:
        """
        Retrieve all IP access control rules on the account.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListIpAclsResponse]
            List of IP ACLs
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/trunks/ip-acl",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListIpAclsResponse,
                    parse_obj_as(
                        type_=ListIpAclsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_ip_acl(
        self,
        auth_id: str,
        ip_acl_id: str,
        *,
        name: str,
        ip_address: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[UpdateIpAclResponse]:
        """
        Update an existing IP access control rule.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        ip_acl_id : str

        name : str

        ip_address : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[UpdateIpAclResponse]
            IP ACL updated
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/ip-acl/{encode_path_param(ip_acl_id)}",
            method="PUT",
            json={
                "name": name,
                "ip_address": ip_address,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    UpdateIpAclResponse,
                    parse_obj_as(
                        type_=UpdateIpAclResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_ip_acl(
        self, auth_id: str, ip_acl_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Optional[str]]:
        """
        Remove an IP access control rule.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        ip_acl_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Optional[str]]
            Success
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/Account/{encode_path_param(auth_id)}/ip-acl/{encode_path_param(ip_acl_id)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[str],
                    parse_obj_as(
                        type_=typing.Optional[str],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
