# This file was auto-generated by Fern from our API Definition.

import typing

CreateSubaccountRequestBusinessType = typing.Union[
    typing.Literal[
        "individual",
        "proprietorship",
        "private_limited",
        "llp",
        "partnership",
        "public_limited",
        "trust",
        "society",
        "huf",
        "government",
    ],
    typing.Any,
]
