# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawRecordCallsClient, RawRecordCallsClient
from .types.start_recording_request_file_format import StartRecordingRequestFileFormat
from .types.start_recording_request_record_channel_type import StartRecordingRequestRecordChannelType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RecordCallsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawRecordCallsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawRecordCallsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawRecordCallsClient
        """
        return self._raw_client

    def start_recording(
        self,
        auth_id: str,
        call_uuid: str,
        *,
        time_limit: typing.Optional[int] = OMIT,
        file_format: typing.Optional[StartRecordingRequestFileFormat] = OMIT,
        transcription_type: typing.Optional[str] = OMIT,
        callback_url: typing.Optional[str] = OMIT,
        record_channel_type: typing.Optional[StartRecordingRequestRecordChannelType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Begin recording an active call. Set format, enable transcription, and configure a callback URL.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        call_uuid : str

        time_limit : typing.Optional[int]

        file_format : typing.Optional[StartRecordingRequestFileFormat]

        transcription_type : typing.Optional[str]
            Set to `auto` to enable transcription

        callback_url : typing.Optional[str]

        record_channel_type : typing.Optional[StartRecordingRequestRecordChannelType]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Recording started

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.record_calls.start_recording(
            auth_id="MA_XXXXXX",
            call_uuid="cdr_XXXXXXXXXX",
            time_limit=120,
            file_format="mp3",
        )
        """
        _response = self._raw_client.start_recording(
            auth_id,
            call_uuid,
            time_limit=time_limit,
            file_format=file_format,
            transcription_type=transcription_type,
            callback_url=callback_url,
            record_channel_type=record_channel_type,
            request_options=request_options,
        )
        return _response.data

    def stop_recording(
        self, auth_id: str, call_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Stop an active recording on an in-progress call.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        call_uuid : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.record_calls.stop_recording(
            auth_id="MA_XXXXXX",
            call_uuid="call_uuid",
        )
        """
        _response = self._raw_client.stop_recording(auth_id, call_uuid, request_options=request_options)
        return _response.data


class AsyncRecordCallsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawRecordCallsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawRecordCallsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawRecordCallsClient
        """
        return self._raw_client

    async def start_recording(
        self,
        auth_id: str,
        call_uuid: str,
        *,
        time_limit: typing.Optional[int] = OMIT,
        file_format: typing.Optional[StartRecordingRequestFileFormat] = OMIT,
        transcription_type: typing.Optional[str] = OMIT,
        callback_url: typing.Optional[str] = OMIT,
        record_channel_type: typing.Optional[StartRecordingRequestRecordChannelType] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Begin recording an active call. Set format, enable transcription, and configure a callback URL.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        call_uuid : str

        time_limit : typing.Optional[int]

        file_format : typing.Optional[StartRecordingRequestFileFormat]

        transcription_type : typing.Optional[str]
            Set to `auto` to enable transcription

        callback_url : typing.Optional[str]

        record_channel_type : typing.Optional[StartRecordingRequestRecordChannelType]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Recording started

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.record_calls.start_recording(
                auth_id="MA_XXXXXX",
                call_uuid="cdr_XXXXXXXXXX",
                time_limit=120,
                file_format="mp3",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start_recording(
            auth_id,
            call_uuid,
            time_limit=time_limit,
            file_format=file_format,
            transcription_type=transcription_type,
            callback_url=callback_url,
            record_channel_type=record_channel_type,
            request_options=request_options,
        )
        return _response.data

    async def stop_recording(
        self, auth_id: str, call_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Stop an active recording on an in-progress call.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        call_uuid : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.record_calls.stop_recording(
                auth_id="MA_XXXXXX",
                call_uuid="call_uuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.stop_recording(auth_id, call_uuid, request_options=request_options)
        return _response.data
