# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        CreateKycSessionRequestFlowType,
        CreateKycSessionRequestReminderScheduleItem,
        CreateKycSessionRequestReminderScheduleItemTrigger,
        GetPartnerDashboardResponse,
        GetPartnerDashboardResponseAccounts,
        GetPartnerDashboardResponseAccountsCustomersItem,
        GetPartnerDashboardResponseByProduct,
        GetPartnerDashboardResponseByProductSipTrunking,
        GetPartnerDashboardResponseByProductVoiceApi,
        GetPartnerDashboardResponseCalls,
        GetPartnerDashboardResponsePartner,
        GetPartnerDashboardResponsePeriod,
        GetPartnerDashboardResponseTimeSeriesItem,
        GetPartnerDashboardResponseTimeSeriesItemInbound,
        GetPartnerDashboardResponseTimeSeriesItemOutbound,
        GetPartnerDashboardResponseTraffic,
        GetPartnerDashboardResponseTrafficInbound,
        GetPartnerDashboardResponseTrafficOutbound,
        GetPartnerProfileResponse,
        ListCustomerAccountsResponse,
        ListCustomerAccountsResponseAccountsItem,
        ListCustomerAccountsResponseAccountsItemPricingTier,
        ListCustomerCdrsRequestCallDirection,
        ListCustomerCdrsRequestStatus,
        ListCustomerCdrsResponse,
        ListCustomerCdrsResponsePagination,
        ListCustomerCdrsResponseSummary,
        ListCustomerNumbersResponse,
        ListCustomerTransactionsRequestTransactionType,
        ListCustomerTransactionsResponse,
        ListCustomerTransactionsResponseSummary,
        ListCustomerTransactionsResponseSummaryByReferenceTypeItem,
        ListCustomerTransactionsResponseTransactionsItem,
        ListKycSessionsRequestStatus,
        ListKycSessionsResponse,
        ListKycSessionsResponseSessionsItem,
        ListKycSessionsResponseSessionsItemMetadata,
        ListKycSessionsResponseSessionsItemMetadataCustomerRef,
        ListKycSessionsResponseSessionsItemReminderScheduleItem,
        ListKycSessionsResponseSessionsItemVerifiedData,
        ListKycSessionsResponseSessionsItemVerifiedDataAadhaarDob,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "CreateKycSessionRequestFlowType": ".types",
    "CreateKycSessionRequestReminderScheduleItem": ".types",
    "CreateKycSessionRequestReminderScheduleItemTrigger": ".types",
    "GetPartnerDashboardResponse": ".types",
    "GetPartnerDashboardResponseAccounts": ".types",
    "GetPartnerDashboardResponseAccountsCustomersItem": ".types",
    "GetPartnerDashboardResponseByProduct": ".types",
    "GetPartnerDashboardResponseByProductSipTrunking": ".types",
    "GetPartnerDashboardResponseByProductVoiceApi": ".types",
    "GetPartnerDashboardResponseCalls": ".types",
    "GetPartnerDashboardResponsePartner": ".types",
    "GetPartnerDashboardResponsePeriod": ".types",
    "GetPartnerDashboardResponseTimeSeriesItem": ".types",
    "GetPartnerDashboardResponseTimeSeriesItemInbound": ".types",
    "GetPartnerDashboardResponseTimeSeriesItemOutbound": ".types",
    "GetPartnerDashboardResponseTraffic": ".types",
    "GetPartnerDashboardResponseTrafficInbound": ".types",
    "GetPartnerDashboardResponseTrafficOutbound": ".types",
    "GetPartnerProfileResponse": ".types",
    "ListCustomerAccountsResponse": ".types",
    "ListCustomerAccountsResponseAccountsItem": ".types",
    "ListCustomerAccountsResponseAccountsItemPricingTier": ".types",
    "ListCustomerCdrsRequestCallDirection": ".types",
    "ListCustomerCdrsRequestStatus": ".types",
    "ListCustomerCdrsResponse": ".types",
    "ListCustomerCdrsResponsePagination": ".types",
    "ListCustomerCdrsResponseSummary": ".types",
    "ListCustomerNumbersResponse": ".types",
    "ListCustomerTransactionsRequestTransactionType": ".types",
    "ListCustomerTransactionsResponse": ".types",
    "ListCustomerTransactionsResponseSummary": ".types",
    "ListCustomerTransactionsResponseSummaryByReferenceTypeItem": ".types",
    "ListCustomerTransactionsResponseTransactionsItem": ".types",
    "ListKycSessionsRequestStatus": ".types",
    "ListKycSessionsResponse": ".types",
    "ListKycSessionsResponseSessionsItem": ".types",
    "ListKycSessionsResponseSessionsItemMetadata": ".types",
    "ListKycSessionsResponseSessionsItemMetadataCustomerRef": ".types",
    "ListKycSessionsResponseSessionsItemReminderScheduleItem": ".types",
    "ListKycSessionsResponseSessionsItemVerifiedData": ".types",
    "ListKycSessionsResponseSessionsItemVerifiedDataAadhaarDob": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateKycSessionRequestFlowType",
    "CreateKycSessionRequestReminderScheduleItem",
    "CreateKycSessionRequestReminderScheduleItemTrigger",
    "GetPartnerDashboardResponse",
    "GetPartnerDashboardResponseAccounts",
    "GetPartnerDashboardResponseAccountsCustomersItem",
    "GetPartnerDashboardResponseByProduct",
    "GetPartnerDashboardResponseByProductSipTrunking",
    "GetPartnerDashboardResponseByProductVoiceApi",
    "GetPartnerDashboardResponseCalls",
    "GetPartnerDashboardResponsePartner",
    "GetPartnerDashboardResponsePeriod",
    "GetPartnerDashboardResponseTimeSeriesItem",
    "GetPartnerDashboardResponseTimeSeriesItemInbound",
    "GetPartnerDashboardResponseTimeSeriesItemOutbound",
    "GetPartnerDashboardResponseTraffic",
    "GetPartnerDashboardResponseTrafficInbound",
    "GetPartnerDashboardResponseTrafficOutbound",
    "GetPartnerProfileResponse",
    "ListCustomerAccountsResponse",
    "ListCustomerAccountsResponseAccountsItem",
    "ListCustomerAccountsResponseAccountsItemPricingTier",
    "ListCustomerCdrsRequestCallDirection",
    "ListCustomerCdrsRequestStatus",
    "ListCustomerCdrsResponse",
    "ListCustomerCdrsResponsePagination",
    "ListCustomerCdrsResponseSummary",
    "ListCustomerNumbersResponse",
    "ListCustomerTransactionsRequestTransactionType",
    "ListCustomerTransactionsResponse",
    "ListCustomerTransactionsResponseSummary",
    "ListCustomerTransactionsResponseSummaryByReferenceTypeItem",
    "ListCustomerTransactionsResponseTransactionsItem",
    "ListKycSessionsRequestStatus",
    "ListKycSessionsResponse",
    "ListKycSessionsResponseSessionsItem",
    "ListKycSessionsResponseSessionsItemMetadata",
    "ListKycSessionsResponseSessionsItemMetadataCustomerRef",
    "ListKycSessionsResponseSessionsItemReminderScheduleItem",
    "ListKycSessionsResponseSessionsItemVerifiedData",
    "ListKycSessionsResponseSessionsItemVerifiedDataAadhaarDob",
]
