# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawPartnerApiClient, RawPartnerApiClient
from .types.create_kyc_session_request_flow_type import CreateKycSessionRequestFlowType
from .types.create_kyc_session_request_reminder_schedule_item import CreateKycSessionRequestReminderScheduleItem
from .types.get_partner_dashboard_response import GetPartnerDashboardResponse
from .types.get_partner_profile_response import GetPartnerProfileResponse
from .types.list_customer_accounts_response import ListCustomerAccountsResponse
from .types.list_customer_cdrs_request_call_direction import ListCustomerCdrsRequestCallDirection
from .types.list_customer_cdrs_request_status import ListCustomerCdrsRequestStatus
from .types.list_customer_cdrs_response import ListCustomerCdrsResponse
from .types.list_customer_numbers_response import ListCustomerNumbersResponse
from .types.list_customer_transactions_request_transaction_type import ListCustomerTransactionsRequestTransactionType
from .types.list_customer_transactions_response import ListCustomerTransactionsResponse
from .types.list_kyc_sessions_request_status import ListKycSessionsRequestStatus
from .types.list_kyc_sessions_response import ListKycSessionsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PartnerApiClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPartnerApiClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPartnerApiClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPartnerApiClient
        """
        return self._raw_client

    def get_partner_profile(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPartnerProfileResponse:
        """
        Returns the authenticated partner's profile and balance.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPartnerProfileResponse
            Partner profile

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.partner_api.get_partner_profile()
        """
        _response = self._raw_client.get_partner_profile(request_options=request_options)
        return _response.data

    def get_partner_dashboard(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPartnerDashboardResponse:
        """
        Aggregated partner metrics - total customers, active accounts, balance
        held across the partner ecosystem, MTD revenue, etc.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPartnerDashboardResponse
            Dashboard summary

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.partner_api.get_partner_dashboard()
        """
        _response = self._raw_client.get_partner_dashboard(request_options=request_options)
        return _response.data

    def list_customer_accounts(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCustomerAccountsResponse:
        """
        Returns all customer sub-accounts under your partner account.

        Parameters
        ----------
        page : typing.Optional[int]

        per_page : typing.Optional[int]

        search : typing.Optional[str]
            Substring match on name or email.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCustomerAccountsResponse
            Customer accounts

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.partner_api.list_customer_accounts()
        """
        _response = self._raw_client.list_customer_accounts(
            page=page, per_page=per_page, search=search, request_options=request_options
        )
        return _response.data

    def create_customer_account(
        self,
        *,
        name: str,
        email: str,
        phone: str,
        password: str,
        country: str,
        company: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Creates a new customer sub-account under your partner account. VoBiz
        emails the customer their login credentials and (separately) a KYC link
        via the kyc-sessions endpoint.

        Parameters
        ----------
        name : str
            Customer's full name.

        email : str
            Customer's email. KYC link is sent here.

        phone : str
            E.164 format.

        password : str
            Min 8 chars, must include a number and a special character.

        country : str
            ISO 2-letter country code.

        company : typing.Optional[str]
            Legal company or business name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Customer account created

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.partner_api.create_customer_account(
            name="John Doe",
            email="john@example.com",
            phone="+919876543210",
            password="SecurePass123!",
            country="IN",
        )
        """
        _response = self._raw_client.create_customer_account(
            name=name,
            email=email,
            phone=phone,
            password=password,
            country=country,
            company=company,
            request_options=request_options,
        )
        return _response.data

    def partner_transfer_balance(
        self,
        customer_auth_id: str,
        *,
        amount: float,
        currency: str,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Atomically debits your partner master balance and credits the customer's
        wallet. Both legs are recorded in each account's ledger. Transfers are
        **permanent and cannot be reversed.**

        Parameters
        ----------
        customer_auth_id : str

        amount : float
            Positive decimal. Your master balance must be ≥ this amount.

        currency : str
            Must match your partner account currency.

        description : typing.Optional[str]
            Note for your records. Appears in both ledgers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Transfer completed

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.partner_api.partner_transfer_balance(
            customer_auth_id="MA_ZKITB8Z2",
            amount=500.0,
            currency="INR",
        )
        """
        _response = self._raw_client.partner_transfer_balance(
            customer_auth_id, amount=amount, currency=currency, description=description, request_options=request_options
        )
        return _response.data

    def list_customer_transactions(
        self,
        customer_auth_id: str,
        *,
        from_date: typing.Optional[dt.date] = None,
        to_date: typing.Optional[dt.date] = None,
        transaction_type: typing.Optional[ListCustomerTransactionsRequestTransactionType] = None,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCustomerTransactionsResponse:
        """
        Returns the customer's transaction ledger. Filter by date range or
        transaction type. Useful for billing reconciliation.

        Parameters
        ----------
        customer_auth_id : str

        from_date : typing.Optional[dt.date]

        to_date : typing.Optional[dt.date]

        transaction_type : typing.Optional[ListCustomerTransactionsRequestTransactionType]

        page : typing.Optional[int]

        per_page : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCustomerTransactionsResponse
            Transactions list

        Examples
        --------
        import datetime

        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.partner_api.list_customer_transactions(
            customer_auth_id="customer_auth_id",
            from_date=datetime.date.fromisoformat(
                "2026-03-01",
            ),
            to_date=datetime.date.fromisoformat(
                "2026-03-31",
            ),
        )
        """
        _response = self._raw_client.list_customer_transactions(
            customer_auth_id,
            from_date=from_date,
            to_date=to_date,
            transaction_type=transaction_type,
            page=page,
            per_page=per_page,
            request_options=request_options,
        )
        return _response.data

    def list_customer_cdrs(
        self,
        customer_auth_id: str,
        *,
        start_date: typing.Optional[dt.date] = None,
        end_date: typing.Optional[dt.date] = None,
        call_direction: typing.Optional[ListCustomerCdrsRequestCallDirection] = None,
        status: typing.Optional[ListCustomerCdrsRequestStatus] = None,
        min_duration: typing.Optional[int] = None,
        hangup_cause: typing.Optional[str] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCustomerCdrsResponse:
        """
        Look up any customer's call history. Same filter set as the
        customer-side CDR endpoint.

        Parameters
        ----------
        customer_auth_id : str

        start_date : typing.Optional[dt.date]

        end_date : typing.Optional[dt.date]

        call_direction : typing.Optional[ListCustomerCdrsRequestCallDirection]

        status : typing.Optional[ListCustomerCdrsRequestStatus]

        min_duration : typing.Optional[int]

        hangup_cause : typing.Optional[str]

        per_page : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCustomerCdrsResponse
            Customer CDRs

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.partner_api.list_customer_cdrs(
            customer_auth_id="customer_auth_id",
            hangup_cause="NO_ANSWER",
        )
        """
        _response = self._raw_client.list_customer_cdrs(
            customer_auth_id,
            start_date=start_date,
            end_date=end_date,
            call_direction=call_direction,
            status=status,
            min_duration=min_duration,
            hangup_cause=hangup_cause,
            per_page=per_page,
            request_options=request_options,
        )
        return _response.data

    def list_customer_numbers(
        self,
        customer_auth_id: str,
        *,
        search: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCustomerNumbersResponse:
        """
        Phone numbers currently assigned to a customer account.

        Parameters
        ----------
        customer_auth_id : str

        search : typing.Optional[str]
            Substring match against the E.164 number.

        page : typing.Optional[int]

        per_page : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCustomerNumbersResponse
            Customer numbers

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.partner_api.list_customer_numbers(
            customer_auth_id="customer_auth_id",
        )
        """
        _response = self._raw_client.list_customer_numbers(
            customer_auth_id, search=search, page=page, per_page=per_page, request_options=request_options
        )
        return _response.data

    def list_kyc_sessions(
        self,
        *,
        status: typing.Optional[ListKycSessionsRequestStatus] = None,
        account_auth_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListKycSessionsResponse:
        """
        Parameters
        ----------
        status : typing.Optional[ListKycSessionsRequestStatus]

        account_auth_id : typing.Optional[str]

        page : typing.Optional[int]

        size : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListKycSessionsResponse
            Sessions list

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.partner_api.list_kyc_sessions()
        """
        _response = self._raw_client.list_kyc_sessions(
            status=status, account_auth_id=account_auth_id, page=page, size=size, request_options=request_options
        )
        return _response.data

    def create_kyc_session(
        self,
        *,
        account_auth_id: str,
        flow_type: typing.Optional[CreateKycSessionRequestFlowType] = OMIT,
        customer_email: typing.Optional[str] = OMIT,
        redirect_url: typing.Optional[str] = OMIT,
        webhook_url: typing.Optional[str] = OMIT,
        expires_in_days: typing.Optional[int] = OMIT,
        reminder_schedule: typing.Optional[typing.Sequence[CreateKycSessionRequestReminderScheduleItem]] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Triggers VoBiz to email a KYC link to the customer. KYC is OTP-based
        (PAN + Aadhaar via DigiLocker for individuals, PAN + GSTIN for
        companies). No document uploads required.

        Parameters
        ----------
        account_auth_id : str
            Customer's auth_id (from create-customer-account).

        flow_type : typing.Optional[CreateKycSessionRequestFlowType]
            Delivery mode. `email` (default) emails the customer the KYC link.
            `redirect` returns a `widget_url` in the response for immediate redirect.

        customer_email : typing.Optional[str]
            Required when `flow_type` is `email`. Ignored otherwise.

        redirect_url : typing.Optional[str]
            Required when `flow_type` is `redirect`. After verification the customer's
            browser is sent to this URL with query params `session_id`, `status`, `auth_id`.

        webhook_url : typing.Optional[str]
            VoBiz POSTs the KYC result here.

        expires_in_days : typing.Optional[int]
            Days before the KYC link expires.

        reminder_schedule : typing.Optional[typing.Sequence[CreateKycSessionRequestReminderScheduleItem]]
            Auto reminder emails before expiry. Email flow only.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Free-form key/value object echoed back on GET and webhooks.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            KYC session created

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.partner_api.create_kyc_session(
            account_auth_id="MA_ZKITB8Z2",
        )
        """
        _response = self._raw_client.create_kyc_session(
            account_auth_id=account_auth_id,
            flow_type=flow_type,
            customer_email=customer_email,
            redirect_url=redirect_url,
            webhook_url=webhook_url,
            expires_in_days=expires_in_days,
            reminder_schedule=reminder_schedule,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def get_kyc_session(self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Parameters
        ----------
        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.partner_api.get_kyc_session(
            session_id="session_id",
        )
        """
        _response = self._raw_client.get_kyc_session(session_id, request_options=request_options)
        return _response.data

    def revoke_kyc_session(
        self,
        session_id: str,
        *,
        reason: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Cancels an outstanding KYC session. Customer can no longer use the link.

        Parameters
        ----------
        session_id : str

        reason : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Session revoked

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.partner_api.revoke_kyc_session(
            session_id="session_id",
        )
        """
        _response = self._raw_client.revoke_kyc_session(session_id, reason=reason, request_options=request_options)
        return _response.data

    def resend_kyc_session(self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Re-dispatches the KYC link to the customer. Rate-limited to once per 30 minutes.

        Parameters
        ----------
        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.partner_api.resend_kyc_session(
            session_id="session_id",
        )
        """
        _response = self._raw_client.resend_kyc_session(session_id, request_options=request_options)
        return _response.data


class AsyncPartnerApiClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPartnerApiClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPartnerApiClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPartnerApiClient
        """
        return self._raw_client

    async def get_partner_profile(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPartnerProfileResponse:
        """
        Returns the authenticated partner's profile and balance.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPartnerProfileResponse
            Partner profile

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.partner_api.get_partner_profile()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_partner_profile(request_options=request_options)
        return _response.data

    async def get_partner_dashboard(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetPartnerDashboardResponse:
        """
        Aggregated partner metrics - total customers, active accounts, balance
        held across the partner ecosystem, MTD revenue, etc.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetPartnerDashboardResponse
            Dashboard summary

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.partner_api.get_partner_dashboard()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_partner_dashboard(request_options=request_options)
        return _response.data

    async def list_customer_accounts(
        self,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCustomerAccountsResponse:
        """
        Returns all customer sub-accounts under your partner account.

        Parameters
        ----------
        page : typing.Optional[int]

        per_page : typing.Optional[int]

        search : typing.Optional[str]
            Substring match on name or email.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCustomerAccountsResponse
            Customer accounts

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.partner_api.list_customer_accounts()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_customer_accounts(
            page=page, per_page=per_page, search=search, request_options=request_options
        )
        return _response.data

    async def create_customer_account(
        self,
        *,
        name: str,
        email: str,
        phone: str,
        password: str,
        country: str,
        company: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Creates a new customer sub-account under your partner account. VoBiz
        emails the customer their login credentials and (separately) a KYC link
        via the kyc-sessions endpoint.

        Parameters
        ----------
        name : str
            Customer's full name.

        email : str
            Customer's email. KYC link is sent here.

        phone : str
            E.164 format.

        password : str
            Min 8 chars, must include a number and a special character.

        country : str
            ISO 2-letter country code.

        company : typing.Optional[str]
            Legal company or business name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Customer account created

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.partner_api.create_customer_account(
                name="John Doe",
                email="john@example.com",
                phone="+919876543210",
                password="SecurePass123!",
                country="IN",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_customer_account(
            name=name,
            email=email,
            phone=phone,
            password=password,
            country=country,
            company=company,
            request_options=request_options,
        )
        return _response.data

    async def partner_transfer_balance(
        self,
        customer_auth_id: str,
        *,
        amount: float,
        currency: str,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Atomically debits your partner master balance and credits the customer's
        wallet. Both legs are recorded in each account's ledger. Transfers are
        **permanent and cannot be reversed.**

        Parameters
        ----------
        customer_auth_id : str

        amount : float
            Positive decimal. Your master balance must be ≥ this amount.

        currency : str
            Must match your partner account currency.

        description : typing.Optional[str]
            Note for your records. Appears in both ledgers.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Transfer completed

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.partner_api.partner_transfer_balance(
                customer_auth_id="MA_ZKITB8Z2",
                amount=500.0,
                currency="INR",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.partner_transfer_balance(
            customer_auth_id, amount=amount, currency=currency, description=description, request_options=request_options
        )
        return _response.data

    async def list_customer_transactions(
        self,
        customer_auth_id: str,
        *,
        from_date: typing.Optional[dt.date] = None,
        to_date: typing.Optional[dt.date] = None,
        transaction_type: typing.Optional[ListCustomerTransactionsRequestTransactionType] = None,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCustomerTransactionsResponse:
        """
        Returns the customer's transaction ledger. Filter by date range or
        transaction type. Useful for billing reconciliation.

        Parameters
        ----------
        customer_auth_id : str

        from_date : typing.Optional[dt.date]

        to_date : typing.Optional[dt.date]

        transaction_type : typing.Optional[ListCustomerTransactionsRequestTransactionType]

        page : typing.Optional[int]

        per_page : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCustomerTransactionsResponse
            Transactions list

        Examples
        --------
        import asyncio
        import datetime

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.partner_api.list_customer_transactions(
                customer_auth_id="customer_auth_id",
                from_date=datetime.date.fromisoformat(
                    "2026-03-01",
                ),
                to_date=datetime.date.fromisoformat(
                    "2026-03-31",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_customer_transactions(
            customer_auth_id,
            from_date=from_date,
            to_date=to_date,
            transaction_type=transaction_type,
            page=page,
            per_page=per_page,
            request_options=request_options,
        )
        return _response.data

    async def list_customer_cdrs(
        self,
        customer_auth_id: str,
        *,
        start_date: typing.Optional[dt.date] = None,
        end_date: typing.Optional[dt.date] = None,
        call_direction: typing.Optional[ListCustomerCdrsRequestCallDirection] = None,
        status: typing.Optional[ListCustomerCdrsRequestStatus] = None,
        min_duration: typing.Optional[int] = None,
        hangup_cause: typing.Optional[str] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCustomerCdrsResponse:
        """
        Look up any customer's call history. Same filter set as the
        customer-side CDR endpoint.

        Parameters
        ----------
        customer_auth_id : str

        start_date : typing.Optional[dt.date]

        end_date : typing.Optional[dt.date]

        call_direction : typing.Optional[ListCustomerCdrsRequestCallDirection]

        status : typing.Optional[ListCustomerCdrsRequestStatus]

        min_duration : typing.Optional[int]

        hangup_cause : typing.Optional[str]

        per_page : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCustomerCdrsResponse
            Customer CDRs

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.partner_api.list_customer_cdrs(
                customer_auth_id="customer_auth_id",
                hangup_cause="NO_ANSWER",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_customer_cdrs(
            customer_auth_id,
            start_date=start_date,
            end_date=end_date,
            call_direction=call_direction,
            status=status,
            min_duration=min_duration,
            hangup_cause=hangup_cause,
            per_page=per_page,
            request_options=request_options,
        )
        return _response.data

    async def list_customer_numbers(
        self,
        customer_auth_id: str,
        *,
        search: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCustomerNumbersResponse:
        """
        Phone numbers currently assigned to a customer account.

        Parameters
        ----------
        customer_auth_id : str

        search : typing.Optional[str]
            Substring match against the E.164 number.

        page : typing.Optional[int]

        per_page : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCustomerNumbersResponse
            Customer numbers

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.partner_api.list_customer_numbers(
                customer_auth_id="customer_auth_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_customer_numbers(
            customer_auth_id, search=search, page=page, per_page=per_page, request_options=request_options
        )
        return _response.data

    async def list_kyc_sessions(
        self,
        *,
        status: typing.Optional[ListKycSessionsRequestStatus] = None,
        account_auth_id: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        size: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListKycSessionsResponse:
        """
        Parameters
        ----------
        status : typing.Optional[ListKycSessionsRequestStatus]

        account_auth_id : typing.Optional[str]

        page : typing.Optional[int]

        size : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListKycSessionsResponse
            Sessions list

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.partner_api.list_kyc_sessions()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_kyc_sessions(
            status=status, account_auth_id=account_auth_id, page=page, size=size, request_options=request_options
        )
        return _response.data

    async def create_kyc_session(
        self,
        *,
        account_auth_id: str,
        flow_type: typing.Optional[CreateKycSessionRequestFlowType] = OMIT,
        customer_email: typing.Optional[str] = OMIT,
        redirect_url: typing.Optional[str] = OMIT,
        webhook_url: typing.Optional[str] = OMIT,
        expires_in_days: typing.Optional[int] = OMIT,
        reminder_schedule: typing.Optional[typing.Sequence[CreateKycSessionRequestReminderScheduleItem]] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Triggers VoBiz to email a KYC link to the customer. KYC is OTP-based
        (PAN + Aadhaar via DigiLocker for individuals, PAN + GSTIN for
        companies). No document uploads required.

        Parameters
        ----------
        account_auth_id : str
            Customer's auth_id (from create-customer-account).

        flow_type : typing.Optional[CreateKycSessionRequestFlowType]
            Delivery mode. `email` (default) emails the customer the KYC link.
            `redirect` returns a `widget_url` in the response for immediate redirect.

        customer_email : typing.Optional[str]
            Required when `flow_type` is `email`. Ignored otherwise.

        redirect_url : typing.Optional[str]
            Required when `flow_type` is `redirect`. After verification the customer's
            browser is sent to this URL with query params `session_id`, `status`, `auth_id`.

        webhook_url : typing.Optional[str]
            VoBiz POSTs the KYC result here.

        expires_in_days : typing.Optional[int]
            Days before the KYC link expires.

        reminder_schedule : typing.Optional[typing.Sequence[CreateKycSessionRequestReminderScheduleItem]]
            Auto reminder emails before expiry. Email flow only.

        metadata : typing.Optional[typing.Dict[str, typing.Any]]
            Free-form key/value object echoed back on GET and webhooks.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            KYC session created

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.partner_api.create_kyc_session(
                account_auth_id="MA_ZKITB8Z2",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_kyc_session(
            account_auth_id=account_auth_id,
            flow_type=flow_type,
            customer_email=customer_email,
            redirect_url=redirect_url,
            webhook_url=webhook_url,
            expires_in_days=expires_in_days,
            reminder_schedule=reminder_schedule,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def get_kyc_session(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.partner_api.get_kyc_session(
                session_id="session_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_kyc_session(session_id, request_options=request_options)
        return _response.data

    async def revoke_kyc_session(
        self,
        session_id: str,
        *,
        reason: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Cancels an outstanding KYC session. Customer can no longer use the link.

        Parameters
        ----------
        session_id : str

        reason : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Session revoked

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.partner_api.revoke_kyc_session(
                session_id="session_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revoke_kyc_session(
            session_id, reason=reason, request_options=request_options
        )
        return _response.data

    async def resend_kyc_session(
        self, session_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Re-dispatches the KYC link to the customer. Rate-limited to once per 30 minutes.

        Parameters
        ----------
        session_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.partner_api.resend_kyc_session(
                session_id="session_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.resend_kyc_session(session_id, request_options=request_options)
        return _response.data
