# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..types.kyc_verification_result import KycVerificationResult
from .types.mock_finalize_pending_kyc_request_outcome import MockFinalizePendingKycRequestOutcome
from .types.mock_finalize_pending_kyc_request_verification_type import MockFinalizePendingKycRequestVerificationType
from .types.mock_subaccount_digilocker_verify_request_access_request_id import (
    MockSubaccountDigilockerVerifyRequestAccessRequestId,
)
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawSubAccountKycTestModeClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def mock_verify_subaccount_pan(
        self, sub_auth_id: str, *, pan: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[KycVerificationResult]:
        """
        Mock PAN verification - never hits the provider. Magic `pan` inputs:

        | Input | Outcome |
        |---|---|
        | `TESTSUCCESS0001` | verified |
        | `TESTFAIL0001` | failed |
        | `TESTERROR0001` | HTTP 500 |
        | `TESTPENDING001` | pending (finalize as verified) |
        | `TESTPENDING_FAIL` | pending (finalize as failed) |

        Persists a real `kyc_verifications` row and recomputes `kyc_status`.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        pan : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[KycVerificationResult]
            Mock verification result
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/test/{encode_path_param(sub_auth_id)}/kyc/verify-pan",
            method="POST",
            json={
                "pan": pan,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def mock_verify_subaccount_gst(
        self, sub_auth_id: str, *, gstin: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[KycVerificationResult]:
        """
        Mock GST verification. Same magic-input matrix as [Mock verify PAN](#operation/mock-verify-subaccount-pan).

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        gstin : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[KycVerificationResult]
            Mock verification result
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/test/{encode_path_param(sub_auth_id)}/kyc/verify-gst",
            method="POST",
            json={
                "gstin": gstin,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def mock_search_subaccount_cin(
        self, sub_auth_id: str, *, company_name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Any]:
        """
        Returns deterministic fake company matches.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        company_name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            Deterministic fake matches
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/test/{encode_path_param(sub_auth_id)}/kyc/cin/search",
            method="POST",
            json={
                "company_name": company_name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def mock_confirm_subaccount_cin(
        self,
        sub_auth_id: str,
        *,
        company_name: str,
        selected_cin: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[KycVerificationResult]:
        """
        Succeeds when `selected_cin` starts with `U72900KA2024PTC123456`.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        company_name : str

        selected_cin : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[KycVerificationResult]
            Mock verification result
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/test/{encode_path_param(sub_auth_id)}/kyc/cin/confirm",
            method="POST",
            json={
                "company_name": company_name,
                "selected_cin": selected_cin,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def mock_subaccount_digilocker_initiate(
        self, sub_auth_id: str, *, redirect_url: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Any]:
        """
        Returns a deterministic `access_request_id`.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        redirect_url : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            Mock DigiLocker link
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/test/{encode_path_param(sub_auth_id)}/kyc/digilocker/initiate",
            method="POST",
            json={
                "redirect_url": redirect_url,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def mock_subaccount_digilocker_verify(
        self,
        sub_auth_id: str,
        *,
        access_request_id: MockSubaccountDigilockerVerifyRequestAccessRequestId,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[KycVerificationResult]:
        """
        `access_request_id` `MOCK_AR_SUCCESS` → verified; `MOCK_AR_FAIL` → failed.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        access_request_id : MockSubaccountDigilockerVerifyRequestAccessRequestId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[KycVerificationResult]
            Mock verification result
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/test/{encode_path_param(sub_auth_id)}/kyc/digilocker/verify",
            method="POST",
            json={
                "access_request_id": access_request_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def mock_finalize_pending_kyc(
        self,
        sub_auth_id: str,
        *,
        verification_type: MockFinalizePendingKycRequestVerificationType,
        outcome: MockFinalizePendingKycRequestOutcome,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[KycVerificationResult]:
        """
        Promotes the most recent **pending** mock verification of the given
        type to a terminal outcome - this drives the async (`TESTPENDING…`)
        path without webhooks. `verification_type` ∈ `pan | aadhaar | gst | cin`;
        `outcome` ∈ `verified | failed`.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        verification_type : MockFinalizePendingKycRequestVerificationType

        outcome : MockFinalizePendingKycRequestOutcome

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[KycVerificationResult]
            Pending verification finalized
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/test/{encode_path_param(sub_auth_id)}/kyc/finalize-pending",
            method="POST",
            json={
                "verification_type": verification_type,
                "outcome": outcome,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSubAccountKycTestModeClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def mock_verify_subaccount_pan(
        self, sub_auth_id: str, *, pan: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[KycVerificationResult]:
        """
        Mock PAN verification - never hits the provider. Magic `pan` inputs:

        | Input | Outcome |
        |---|---|
        | `TESTSUCCESS0001` | verified |
        | `TESTFAIL0001` | failed |
        | `TESTERROR0001` | HTTP 500 |
        | `TESTPENDING001` | pending (finalize as verified) |
        | `TESTPENDING_FAIL` | pending (finalize as failed) |

        Persists a real `kyc_verifications` row and recomputes `kyc_status`.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        pan : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[KycVerificationResult]
            Mock verification result
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/test/{encode_path_param(sub_auth_id)}/kyc/verify-pan",
            method="POST",
            json={
                "pan": pan,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def mock_verify_subaccount_gst(
        self, sub_auth_id: str, *, gstin: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[KycVerificationResult]:
        """
        Mock GST verification. Same magic-input matrix as [Mock verify PAN](#operation/mock-verify-subaccount-pan).

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        gstin : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[KycVerificationResult]
            Mock verification result
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/test/{encode_path_param(sub_auth_id)}/kyc/verify-gst",
            method="POST",
            json={
                "gstin": gstin,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def mock_search_subaccount_cin(
        self, sub_auth_id: str, *, company_name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Any]:
        """
        Returns deterministic fake company matches.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        company_name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            Deterministic fake matches
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/test/{encode_path_param(sub_auth_id)}/kyc/cin/search",
            method="POST",
            json={
                "company_name": company_name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def mock_confirm_subaccount_cin(
        self,
        sub_auth_id: str,
        *,
        company_name: str,
        selected_cin: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[KycVerificationResult]:
        """
        Succeeds when `selected_cin` starts with `U72900KA2024PTC123456`.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        company_name : str

        selected_cin : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[KycVerificationResult]
            Mock verification result
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/test/{encode_path_param(sub_auth_id)}/kyc/cin/confirm",
            method="POST",
            json={
                "company_name": company_name,
                "selected_cin": selected_cin,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def mock_subaccount_digilocker_initiate(
        self, sub_auth_id: str, *, redirect_url: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Any]:
        """
        Returns a deterministic `access_request_id`.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        redirect_url : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            Mock DigiLocker link
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/test/{encode_path_param(sub_auth_id)}/kyc/digilocker/initiate",
            method="POST",
            json={
                "redirect_url": redirect_url,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def mock_subaccount_digilocker_verify(
        self,
        sub_auth_id: str,
        *,
        access_request_id: MockSubaccountDigilockerVerifyRequestAccessRequestId,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[KycVerificationResult]:
        """
        `access_request_id` `MOCK_AR_SUCCESS` → verified; `MOCK_AR_FAIL` → failed.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        access_request_id : MockSubaccountDigilockerVerifyRequestAccessRequestId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[KycVerificationResult]
            Mock verification result
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/test/{encode_path_param(sub_auth_id)}/kyc/digilocker/verify",
            method="POST",
            json={
                "access_request_id": access_request_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def mock_finalize_pending_kyc(
        self,
        sub_auth_id: str,
        *,
        verification_type: MockFinalizePendingKycRequestVerificationType,
        outcome: MockFinalizePendingKycRequestOutcome,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[KycVerificationResult]:
        """
        Promotes the most recent **pending** mock verification of the given
        type to a terminal outcome - this drives the async (`TESTPENDING…`)
        path without webhooks. `verification_type` ∈ `pan | aadhaar | gst | cin`;
        `outcome` ∈ `verified | failed`.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        verification_type : MockFinalizePendingKycRequestVerificationType

        outcome : MockFinalizePendingKycRequestOutcome

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[KycVerificationResult]
            Pending verification finalized
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/test/{encode_path_param(sub_auth_id)}/kyc/finalize-pending",
            method="POST",
            json={
                "verification_type": verification_type,
                "outcome": outcome,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
