# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .cancel_number_release_response import CancelNumberReleaseResponse
    from .cancel_number_release_response_refund_status import CancelNumberReleaseResponseRefundStatus
    from .cancel_number_release_response_status import CancelNumberReleaseResponseStatus
    from .get_number_health_request_granularity import GetNumberHealthRequestGranularity
    from .get_number_health_response import GetNumberHealthResponse
    from .get_number_health_response_snapshots_item import GetNumberHealthResponseSnapshotsItem
    from .get_number_health_response_summary import GetNumberHealthResponseSummary
    from .list_inventory_numbers_response import ListInventoryNumbersResponse
    from .list_inventory_numbers_response_items_item import ListInventoryNumbersResponseItemsItem
    from .list_inventory_numbers_response_items_item_capabilities import (
        ListInventoryNumbersResponseItemsItemCapabilities,
    )
    from .list_numbers_response import ListNumbersResponse
    from .list_numbers_response_items_item import ListNumbersResponseItemsItem
    from .list_numbers_response_items_item_capabilities import ListNumbersResponseItemsItemCapabilities
    from .unrent_number_response import UnrentNumberResponse
_dynamic_imports: typing.Dict[str, str] = {
    "CancelNumberReleaseResponse": ".cancel_number_release_response",
    "CancelNumberReleaseResponseRefundStatus": ".cancel_number_release_response_refund_status",
    "CancelNumberReleaseResponseStatus": ".cancel_number_release_response_status",
    "GetNumberHealthRequestGranularity": ".get_number_health_request_granularity",
    "GetNumberHealthResponse": ".get_number_health_response",
    "GetNumberHealthResponseSnapshotsItem": ".get_number_health_response_snapshots_item",
    "GetNumberHealthResponseSummary": ".get_number_health_response_summary",
    "ListInventoryNumbersResponse": ".list_inventory_numbers_response",
    "ListInventoryNumbersResponseItemsItem": ".list_inventory_numbers_response_items_item",
    "ListInventoryNumbersResponseItemsItemCapabilities": ".list_inventory_numbers_response_items_item_capabilities",
    "ListNumbersResponse": ".list_numbers_response",
    "ListNumbersResponseItemsItem": ".list_numbers_response_items_item",
    "ListNumbersResponseItemsItemCapabilities": ".list_numbers_response_items_item_capabilities",
    "UnrentNumberResponse": ".unrent_number_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CancelNumberReleaseResponse",
    "CancelNumberReleaseResponseRefundStatus",
    "CancelNumberReleaseResponseStatus",
    "GetNumberHealthRequestGranularity",
    "GetNumberHealthResponse",
    "GetNumberHealthResponseSnapshotsItem",
    "GetNumberHealthResponseSummary",
    "ListInventoryNumbersResponse",
    "ListInventoryNumbersResponseItemsItem",
    "ListInventoryNumbersResponseItemsItemCapabilities",
    "ListNumbersResponse",
    "ListNumbersResponseItemsItem",
    "ListNumbersResponseItemsItemCapabilities",
    "UnrentNumberResponse",
]
