# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .cancel_number_release_response_refund_status import CancelNumberReleaseResponseRefundStatus
from .cancel_number_release_response_status import CancelNumberReleaseResponseStatus


class CancelNumberReleaseResponse(UniversalBaseModel):
    message: str
    status: CancelNumberReleaseResponseStatus
    currency: typing.Optional[str] = None
    refund_amount: typing.Optional[float] = None
    refund_status: typing.Optional[CancelNumberReleaseResponseRefundStatus] = None
    refund_error: typing.Optional[str] = pydantic.Field(default=None)
    """
    Present when the refund could not be processed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.forbid
