# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GetNumberHealthResponseSnapshotsItem(UniversalBaseModel):
    id: typing.Optional[str] = None
    ts: typing.Optional[dt.datetime] = None
    total_calls: typing.Optional[int] = None
    answered_calls: typing.Optional[int] = None
    failed_calls: typing.Optional[int] = None
    answer_rate: typing.Optional[float] = None
    total_duration: typing.Optional[float] = None
    avg_duration: typing.Optional[float] = None
    total_minutes: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.forbid
