# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .list_numbers_response_items_item_capabilities import ListNumbersResponseItemsItemCapabilities


class ListNumbersResponseItemsItem(UniversalBaseModel):
    id: str
    account_id: str
    e164: str
    country: str
    region: str
    capabilities: ListNumbersResponseItemsItemCapabilities
    status: str
    provider: str
    setup_fee: int
    monthly_fee: int
    currency: str
    application_id: typing.Optional[str] = None
    voice_enabled: bool
    tags: typing.List[str]
    purchased_at: str
    is_blocked: bool
    created_at: str
    updated_at: str
    is_trial_number: bool
    last_billing_date: typing.Optional[str] = None
    next_billing_date: typing.Optional[str] = None
    minimum_commitment_months: int
    aadhaar_verification_required: bool
    aadhaar_verified: bool
    source: str
    released_at: typing.Optional[str] = None
    trunk_group_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.forbid
