# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .account_account_type import AccountAccountType


class Account(UniversalBaseModel):
    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    auth_id: typing.Optional[str] = None
    account_type: typing.Optional[AccountAccountType] = None
    enabled: typing.Optional[bool] = None
    is_active: typing.Optional[bool] = None
    cps_limit: typing.Optional[int] = None
    concurrent_calls_limit: typing.Optional[int] = None
    created_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.forbid
