# This file was auto-generated by Fern from our API Definition.

import typing

CallRecordCallStatus = typing.Union[typing.Literal["answered", "busy", "failed", "no-answer", "cancelled"], typing.Any]
