# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .capacity_resource_type import CapacityResourceType


class ChannelSubscription(UniversalBaseModel):
    id: str
    account_id: int
    resource_type: CapacityResourceType
    quantity: int
    monthly_cost: str = pydantic.Field()
    """
    Recurring monthly charge as a decimal string.
    """

    currency: str
    status: str
    last_billing_date: dt.datetime
    next_billing_date: dt.datetime
    purchased_at: dt.datetime
    cancelled_at: typing.Optional[dt.datetime] = None
    cancellation_reason: typing.Optional[str] = None
    is_active: bool
    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.forbid
