# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .endpoint_application import EndpointApplication
from .endpoint_sip_registered import EndpointSipRegistered


class Endpoint(UniversalBaseModel):
    endpoint_id: typing.Optional[str] = None
    username: typing.Optional[str] = None
    alias: typing.Optional[str] = None
    sip_uri: typing.Optional[str] = None
    sip_registered: typing.Optional[EndpointSipRegistered] = None
    sip_contact: typing.Optional[str] = None
    sip_expires: typing.Optional[dt.datetime] = None
    sip_user_agent: typing.Optional[str] = None
    application: typing.Optional[EndpointApplication] = None
    allow_voice: typing.Optional[bool] = None
    allow_message: typing.Optional[bool] = None
    allow_video: typing.Optional[bool] = None
    allow_same_domain: typing.Optional[bool] = None
    allow_other_domains: typing.Optional[bool] = None
    allow_phones: typing.Optional[bool] = None
    allow_apps: typing.Optional[bool] = None
    sub_account: typing.Optional[str] = None
    resource_uri: typing.Optional[str] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.forbid
