# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .partner_customer_status import PartnerCustomerStatus


class PartnerCustomer(UniversalBaseModel):
    """
    A SIP-enabled customer sub-account under your partner umbrella.
    """

    auth_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Permanent customer identifier - primary key for balance transfers, CDR lookups, transaction queries, and number assignments.
    """

    name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    status: typing.Optional[PartnerCustomerStatus] = None
    balance: typing.Optional[float] = None
    currency: typing.Optional[str] = None
    country: typing.Optional[str] = None
    timezone: typing.Optional[str] = None
    created_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.forbid
