# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .partner_transaction_type import PartnerTransactionType


class PartnerTransaction(UniversalBaseModel):
    """
    A single credit or debit ledger entry on a partner or customer account.
    """

    id: typing.Optional[str] = None
    type: typing.Optional[PartnerTransactionType] = None
    amount: typing.Optional[float] = None
    currency: typing.Optional[str] = None
    balance_before: typing.Optional[float] = None
    balance_after: typing.Optional[float] = None
    description: typing.Optional[str] = None
    initiated_by: typing.Optional[str] = None
    created_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.forbid
