# This file was auto-generated by Fern from our API Definition.

import typing

SubAccountKycStatusVerificationsValue = typing.Union[
    typing.Literal["not_started", "pending", "verified", "failed"], typing.Any
]
