# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .sub_account_kyc_mode import SubAccountKycMode


class SubAccount(UniversalBaseModel):
    auth_id: typing.Optional[str] = None
    auth_token: typing.Optional[str] = None
    name: typing.Optional[str] = None
    enabled: typing.Optional[bool] = None
    kyc_mode: typing.Optional[SubAccountKycMode] = pydantic.Field(default=None)
    """
    Verification mode. `customer_use` sub-accounts must complete their own KYC before placing calls.
    """

    business_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Legal constitution of the customer (e.g. `private_limited`).
    """

    kyc_calls_blocked: typing.Optional[bool] = pydantic.Field(default=None)
    """
    True while a `customer_use` sub-account has not yet completed the KYC required to place calls.
    """

    created_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.forbid
