# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ListEndpointsResponseObjectsItem(UniversalBaseModel):
    alias: str
    application: typing.Optional[str] = None
    endpoint_id: str
    resource_uri: str
    sip_registered: str
    sip_uri: str
    sub_account: typing.Optional[typing.Any] = None
    username: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.forbid
