# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawPhoneNumbersClient, RawPhoneNumbersClient
from .types.cancel_number_release_response import CancelNumberReleaseResponse
from .types.get_number_health_request_granularity import GetNumberHealthRequestGranularity
from .types.get_number_health_response import GetNumberHealthResponse
from .types.list_inventory_numbers_response import ListInventoryNumbersResponse
from .types.list_numbers_response import ListNumbersResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PhoneNumbersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPhoneNumbersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPhoneNumbersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPhoneNumbersClient
        """
        return self._raw_client

    def list_numbers(
        self,
        auth_id: str,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListNumbersResponse:
        """
        List all phone numbers on your account.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        page : typing.Optional[int]
            Page number, starting at 1

        per_page : typing.Optional[int]
            Number of phone numbers to return per page

        search : typing.Optional[str]
            Filter by phone number. Include the country code and URL-encode a leading plus sign.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListNumbersResponse
            List of phone numbers

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )
        client.phone_numbers.list_numbers(
            auth_id="MA_XXXXXX",
            search="+919876543210",
        )
        """
        _response = self._raw_client.list_numbers(
            auth_id, page=page, per_page=per_page, search=search, request_options=request_options
        )
        return _response.data

    def unrent_number(
        self,
        auth_id: str,
        e164: str,
        *,
        immediate: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Release a phone number from your account. By default, the number enters
        `pending_release` for a 24-hour cooldown. You can cancel the release during
        that window. Set `immediate=true` to skip the cooldown; an immediate release
        cannot be cancelled.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        e164 : str
            Phone number in E.164 format (without the +)

        immediate : typing.Optional[bool]
            Skip the 24-hour cooldown and release the number immediately.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )
        client.phone_numbers.unrent_number(
            auth_id="MA_XXXXXX",
            e164="919876543210",
        )
        """
        _response = self._raw_client.unrent_number(auth_id, e164, immediate=immediate, request_options=request_options)
        return _response.data

    def cancel_number_release(
        self, account_id: str, e164: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CancelNumberReleaseResponse:
        """
        Cancel a pending number release during the 24-hour cooldown. The number is
        restored to `active`, the cooldown timer is cleared, and the release fee is
        refunded. Any trunk or voice application detached by the release is not
        re-attached automatically.

        Parameters
        ----------
        account_id : str
            Your account Auth ID.

        e164 : str
            The URL-encoded phone number in E.164 format. Encode `+` as `%2B`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelNumberReleaseResponse
            Release cancelled and number restored to active

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )
        client.phone_numbers.cancel_number_release(
            account_id="MA_XXXXXX",
            e164="%2B919876543210",
        )
        """
        _response = self._raw_client.cancel_number_release(account_id, e164, request_options=request_options)
        return _response.data

    def list_inventory_numbers(
        self,
        auth_id: str,
        *,
        country: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        exclude: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListInventoryNumbersResponse:
        """
        Browse available phone numbers in inventory that are not assigned to
        any account. Only numbers with `status='active'` and `auth_id=NULL`
        are returned. These numbers are ready to be purchased.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        country : typing.Optional[str]
            Filter by country code (e.g., "US", "IN").

        search : typing.Optional[str]
            Substring match against the E.164 number (e.g., "80" matches "+918065...").

        exclude : typing.Optional[str]
            One or more E.164 prefixes to remove from results. Include the country code (e.g. "9180" for India +91 80-series, "1415" for US +1 415); a leading "+" is optional. Matched against the full E.164 form, so it works for any country. Accepts a comma-separated list ("9180,9192") or repeated params ("exclude=9180&exclude=9192"), and the two forms can be combined. It is ANDed with all other filters, so it takes priority over `search`; duplicates are de-duplicated silently and `total` reflects the filtered result set.

        page : typing.Optional[int]

        per_page : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListInventoryNumbersResponse
            Inventory numbers

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )
        client.phone_numbers.list_inventory_numbers(
            auth_id="MA_XXXXXX",
            country="IN",
            exclude="9180,9192",
        )
        """
        _response = self._raw_client.list_inventory_numbers(
            auth_id,
            country=country,
            search=search,
            exclude=exclude,
            page=page,
            per_page=per_page,
            request_options=request_options,
        )
        return _response.data

    def purchase_from_inventory(
        self,
        auth_id: str,
        *,
        e164: str,
        currency: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Purchase a phone number from inventory and assign it to your account.
        Debits your account balance for the setup fee and monthly fee. For
        sub-accounts (SA_), the parent master account (MA_) is charged.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        e164 : str
            Phone number to purchase in E.164 format.

        currency : typing.Optional[str]
            Currency for transaction. Defaults to the number's currency or "USD".

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Number purchased

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )
        client.phone_numbers.purchase_from_inventory(
            auth_id="MA_XXXXXX",
            e164="+919876543210",
            currency="USD",
        )
        """
        _response = self._raw_client.purchase_from_inventory(
            auth_id, e164=e164, currency=currency, request_options=request_options
        )
        return _response.data

    def assign_number_to_trunk(
        self,
        auth_id: str,
        phone_number: str,
        *,
        trunk_group_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Assign a phone number to a specific SIP trunk. Once assigned, all
        inbound calls to that phone number will be routed through the
        designated trunk. The phone number must be URL-encoded; use `%2B`
        instead of `+` (e.g., `%2B912271264217`).

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        phone_number : str
            The phone number to assign, URL-encoded (use %2B instead of +).

        trunk_group_id : str
            The UUID of the trunk to assign this number to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )
        client.phone_numbers.assign_number_to_trunk(
            auth_id="MA_XXXXXX",
            phone_number="%2B912271264217",
            trunk_group_id="e3e55a78-1234-5678-90ab-cdef12345678",
        )
        """
        _response = self._raw_client.assign_number_to_trunk(
            auth_id, phone_number, trunk_group_id=trunk_group_id, request_options=request_options
        )
        return _response.data

    def unassign_number_from_trunk(
        self, auth_id: str, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Remove the assignment between a phone number and a SIP trunk. After
        unassignment, the number remains in your account inventory but will
        no longer route inbound calls through the previously assigned trunk.
        URL-encode the phone number (use `%2B` instead of `+`).

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        phone_number : str
            The phone number to unassign, URL-encoded (use %2B instead of +).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )
        client.phone_numbers.unassign_number_from_trunk(
            auth_id="MA_XXXXXX",
            phone_number="%2B912271264217",
        )
        """
        _response = self._raw_client.unassign_number_from_trunk(auth_id, phone_number, request_options=request_options)
        return _response.data

    def get_number_health(
        self,
        auth_id: str,
        e164: str,
        *,
        granularity: typing.Optional[GetNumberHealthRequestGranularity] = None,
        days: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetNumberHealthResponse:
        """
        Returns the health & analytics dashboard for one of your numbers: current
        status, spam flag, and call metrics over the selected window (total and
        answered calls, answer rate, minutes, average duration) plus a per-period
        time series of snapshots.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        e164 : str
            The number in E.164, URL-encoded (use %2B instead of +).

        granularity : typing.Optional[GetNumberHealthRequestGranularity]
            Snapshot granularity.

        days : typing.Optional[int]
            Size of the window (in days) for the summary and snapshots.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetNumberHealthResponse
            Number health dashboard

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )
        client.phone_numbers.get_number_health(
            auth_id="MA_XXXXXX",
            e164="%2B919876543210",
            days=30,
        )
        """
        _response = self._raw_client.get_number_health(
            auth_id, e164, granularity=granularity, days=days, request_options=request_options
        )
        return _response.data

    def assign_did_to_subaccount(
        self, auth_id: str, e164: str, *, sub_account_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Assign a parent-pool DID to a sub-account.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        e164 : str
            The number in E.164, URL-encoded (use %2B instead of +).

        sub_account_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )
        client.phone_numbers.assign_did_to_subaccount(
            auth_id="MA_XXXXXX",
            e164="%2B919876543210",
            sub_account_id="SA_XXXXXX",
        )
        """
        _response = self._raw_client.assign_did_to_subaccount(
            auth_id, e164, sub_account_id=sub_account_id, request_options=request_options
        )
        return _response.data

    def unassign_did_from_subaccount(
        self,
        auth_id: str,
        e164: str,
        *,
        force: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Move the DID back to the parent pool.

        A **15-day cool-off** is enforced: if the DID had a call within the last
        15 days, the request is rejected with `409` and a
        `did_cool_off_in_effect` error that includes `cool_off_until` and
        `cool_off_remaining_seconds`. Never-used DIDs (`last_call_at` is `NULL`)
        move back immediately.

        Admins can bypass the cool-off with `?force=true` (see below); the
        bypass writes a `did_assignment_audit` row and requires an
        admin-role account.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        e164 : str
            The number in E.164, URL-encoded (use %2B instead of +).

        force : typing.Optional[bool]
            Admin-only cool-off bypass. Requires an admin-role account
            (enforced at the gateway) and writes a `did_assignment_audit` row.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )
        client.phone_numbers.unassign_did_from_subaccount(
            auth_id="MA_XXXXXX",
            e164="%2B919876543210",
            force=True,
        )
        """
        _response = self._raw_client.unassign_did_from_subaccount(
            auth_id, e164, force=force, request_options=request_options
        )
        return _response.data


class AsyncPhoneNumbersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPhoneNumbersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPhoneNumbersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPhoneNumbersClient
        """
        return self._raw_client

    async def list_numbers(
        self,
        auth_id: str,
        *,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        search: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListNumbersResponse:
        """
        List all phone numbers on your account.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        page : typing.Optional[int]
            Page number, starting at 1

        per_page : typing.Optional[int]
            Number of phone numbers to return per page

        search : typing.Optional[str]
            Filter by phone number. Include the country code and URL-encode a leading plus sign.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListNumbersResponse
            List of phone numbers

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.phone_numbers.list_numbers(
                auth_id="MA_XXXXXX",
                search="+919876543210",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_numbers(
            auth_id, page=page, per_page=per_page, search=search, request_options=request_options
        )
        return _response.data

    async def unrent_number(
        self,
        auth_id: str,
        e164: str,
        *,
        immediate: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Release a phone number from your account. By default, the number enters
        `pending_release` for a 24-hour cooldown. You can cancel the release during
        that window. Set `immediate=true` to skip the cooldown; an immediate release
        cannot be cancelled.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        e164 : str
            Phone number in E.164 format (without the +)

        immediate : typing.Optional[bool]
            Skip the 24-hour cooldown and release the number immediately.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.phone_numbers.unrent_number(
                auth_id="MA_XXXXXX",
                e164="919876543210",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.unrent_number(
            auth_id, e164, immediate=immediate, request_options=request_options
        )
        return _response.data

    async def cancel_number_release(
        self, account_id: str, e164: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> CancelNumberReleaseResponse:
        """
        Cancel a pending number release during the 24-hour cooldown. The number is
        restored to `active`, the cooldown timer is cleared, and the release fee is
        refunded. Any trunk or voice application detached by the release is not
        re-attached automatically.

        Parameters
        ----------
        account_id : str
            Your account Auth ID.

        e164 : str
            The URL-encoded phone number in E.164 format. Encode `+` as `%2B`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CancelNumberReleaseResponse
            Release cancelled and number restored to active

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.phone_numbers.cancel_number_release(
                account_id="MA_XXXXXX",
                e164="%2B919876543210",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel_number_release(account_id, e164, request_options=request_options)
        return _response.data

    async def list_inventory_numbers(
        self,
        auth_id: str,
        *,
        country: typing.Optional[str] = None,
        search: typing.Optional[str] = None,
        exclude: typing.Optional[str] = None,
        page: typing.Optional[int] = None,
        per_page: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListInventoryNumbersResponse:
        """
        Browse available phone numbers in inventory that are not assigned to
        any account. Only numbers with `status='active'` and `auth_id=NULL`
        are returned. These numbers are ready to be purchased.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        country : typing.Optional[str]
            Filter by country code (e.g., "US", "IN").

        search : typing.Optional[str]
            Substring match against the E.164 number (e.g., "80" matches "+918065...").

        exclude : typing.Optional[str]
            One or more E.164 prefixes to remove from results. Include the country code (e.g. "9180" for India +91 80-series, "1415" for US +1 415); a leading "+" is optional. Matched against the full E.164 form, so it works for any country. Accepts a comma-separated list ("9180,9192") or repeated params ("exclude=9180&exclude=9192"), and the two forms can be combined. It is ANDed with all other filters, so it takes priority over `search`; duplicates are de-duplicated silently and `total` reflects the filtered result set.

        page : typing.Optional[int]

        per_page : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListInventoryNumbersResponse
            Inventory numbers

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.phone_numbers.list_inventory_numbers(
                auth_id="MA_XXXXXX",
                country="IN",
                exclude="9180,9192",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_inventory_numbers(
            auth_id,
            country=country,
            search=search,
            exclude=exclude,
            page=page,
            per_page=per_page,
            request_options=request_options,
        )
        return _response.data

    async def purchase_from_inventory(
        self,
        auth_id: str,
        *,
        e164: str,
        currency: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Purchase a phone number from inventory and assign it to your account.
        Debits your account balance for the setup fee and monthly fee. For
        sub-accounts (SA_), the parent master account (MA_) is charged.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        e164 : str
            Phone number to purchase in E.164 format.

        currency : typing.Optional[str]
            Currency for transaction. Defaults to the number's currency or "USD".

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Number purchased

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.phone_numbers.purchase_from_inventory(
                auth_id="MA_XXXXXX",
                e164="+919876543210",
                currency="USD",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.purchase_from_inventory(
            auth_id, e164=e164, currency=currency, request_options=request_options
        )
        return _response.data

    async def assign_number_to_trunk(
        self,
        auth_id: str,
        phone_number: str,
        *,
        trunk_group_id: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Assign a phone number to a specific SIP trunk. Once assigned, all
        inbound calls to that phone number will be routed through the
        designated trunk. The phone number must be URL-encoded; use `%2B`
        instead of `+` (e.g., `%2B912271264217`).

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        phone_number : str
            The phone number to assign, URL-encoded (use %2B instead of +).

        trunk_group_id : str
            The UUID of the trunk to assign this number to.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.phone_numbers.assign_number_to_trunk(
                auth_id="MA_XXXXXX",
                phone_number="%2B912271264217",
                trunk_group_id="e3e55a78-1234-5678-90ab-cdef12345678",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.assign_number_to_trunk(
            auth_id, phone_number, trunk_group_id=trunk_group_id, request_options=request_options
        )
        return _response.data

    async def unassign_number_from_trunk(
        self, auth_id: str, phone_number: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Remove the assignment between a phone number and a SIP trunk. After
        unassignment, the number remains in your account inventory but will
        no longer route inbound calls through the previously assigned trunk.
        URL-encode the phone number (use `%2B` instead of `+`).

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        phone_number : str
            The phone number to unassign, URL-encoded (use %2B instead of +).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.phone_numbers.unassign_number_from_trunk(
                auth_id="MA_XXXXXX",
                phone_number="%2B912271264217",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.unassign_number_from_trunk(
            auth_id, phone_number, request_options=request_options
        )
        return _response.data

    async def get_number_health(
        self,
        auth_id: str,
        e164: str,
        *,
        granularity: typing.Optional[GetNumberHealthRequestGranularity] = None,
        days: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetNumberHealthResponse:
        """
        Returns the health & analytics dashboard for one of your numbers: current
        status, spam flag, and call metrics over the selected window (total and
        answered calls, answer rate, minutes, average duration) plus a per-period
        time series of snapshots.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        e164 : str
            The number in E.164, URL-encoded (use %2B instead of +).

        granularity : typing.Optional[GetNumberHealthRequestGranularity]
            Snapshot granularity.

        days : typing.Optional[int]
            Size of the window (in days) for the summary and snapshots.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetNumberHealthResponse
            Number health dashboard

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.phone_numbers.get_number_health(
                auth_id="MA_XXXXXX",
                e164="%2B919876543210",
                days=30,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_number_health(
            auth_id, e164, granularity=granularity, days=days, request_options=request_options
        )
        return _response.data

    async def assign_did_to_subaccount(
        self, auth_id: str, e164: str, *, sub_account_id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Assign a parent-pool DID to a sub-account.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        e164 : str
            The number in E.164, URL-encoded (use %2B instead of +).

        sub_account_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.phone_numbers.assign_did_to_subaccount(
                auth_id="MA_XXXXXX",
                e164="%2B919876543210",
                sub_account_id="SA_XXXXXX",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.assign_did_to_subaccount(
            auth_id, e164, sub_account_id=sub_account_id, request_options=request_options
        )
        return _response.data

    async def unassign_did_from_subaccount(
        self,
        auth_id: str,
        e164: str,
        *,
        force: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Move the DID back to the parent pool.

        A **15-day cool-off** is enforced: if the DID had a call within the last
        15 days, the request is rejected with `409` and a
        `did_cool_off_in_effect` error that includes `cool_off_until` and
        `cool_off_remaining_seconds`. Never-used DIDs (`last_call_at` is `NULL`)
        move back immediately.

        Admins can bypass the cool-off with `?force=true` (see below); the
        bypass writes a `did_assignment_audit` row and requires an
        admin-role account.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        e164 : str
            The number in E.164, URL-encoded (use %2B instead of +).

        force : typing.Optional[bool]
            Admin-only cool-off bypass. Requires an admin-role account
            (enforced at the gateway) and writes a `did_assignment_audit` row.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.phone_numbers.unassign_did_from_subaccount(
                auth_id="MA_XXXXXX",
                e164="%2B919876543210",
                force=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.unassign_did_from_subaccount(
            auth_id, e164, force=force, request_options=request_options
        )
        return _response.data
