# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.kyc_verification_result import KycVerificationResult
from ..types.sub_account_kyc_status import SubAccountKycStatus
from .raw_client import AsyncRawSubAccountKycClient, RawSubAccountKycClient
from .types.create_subaccount_kyc_session_request_flow_type import CreateSubaccountKycSessionRequestFlowType

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SubAccountKycClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSubAccountKycClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSubAccountKycClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSubAccountKycClient
        """
        return self._raw_client

    def get_subaccount_kyc_status(
        self, sub_auth_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SubAccountKycStatus:
        """
        Returns the aggregated KYC state for a `customer_use` sub-account —
        which verifications have passed, whether calls are still blocked, and
        the business type. The caller must be the parent main account that owns
        the sub-account (or an admin).

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubAccountKycStatus
            Aggregated KYC state

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.sub_account_kyc.get_subaccount_kyc_status(
            sub_auth_id="SA_XXXXXX",
        )
        """
        _response = self._raw_client.get_subaccount_kyc_status(sub_auth_id, request_options=request_options)
        return _response.data

    def verify_subaccount_pan(
        self, sub_auth_id: str, *, pan: str, request_options: typing.Optional[RequestOptions] = None
    ) -> KycVerificationResult:
        """
        Runs a real PAN verification (Perfios) for the sub-account. `pan` must
        be exactly 10 characters. Persists a `kyc_verifications` row and
        recomputes the sub-account's aggregated `kyc_status`.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        pan : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KycVerificationResult
            Verification result

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.sub_account_kyc.verify_subaccount_pan(
            sub_auth_id="SA_XXXXXX",
            pan="ABCDE1234F",
        )
        """
        _response = self._raw_client.verify_subaccount_pan(sub_auth_id, pan=pan, request_options=request_options)
        return _response.data

    def verify_subaccount_gst(
        self, sub_auth_id: str, *, gstin: str, request_options: typing.Optional[RequestOptions] = None
    ) -> KycVerificationResult:
        """
        Runs a real GSTIN verification. `gstin` must be a 15-character GSTIN.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        gstin : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KycVerificationResult
            Verification result

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.sub_account_kyc.verify_subaccount_gst(
            sub_auth_id="SA_XXXXXX",
            gstin="29AAJCN5983D1Z0",
        )
        """
        _response = self._raw_client.verify_subaccount_gst(sub_auth_id, gstin=gstin, request_options=request_options)
        return _response.data

    def search_subaccount_cin(
        self, sub_auth_id: str, *, company_name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Name-based CIN lookup. Returns candidate company matches; pick one and
        pass it to [CIN confirm](#operation/confirm-subaccount-cin).

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        company_name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Candidate matches

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.sub_account_kyc.search_subaccount_cin(
            sub_auth_id="SA_XXXXXX",
            company_name="ACME PRIVATE LIMITED",
        )
        """
        _response = self._raw_client.search_subaccount_cin(
            sub_auth_id, company_name=company_name, request_options=request_options
        )
        return _response.data

    def confirm_subaccount_cin(
        self,
        sub_auth_id: str,
        *,
        company_name: str,
        selected_cin: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> KycVerificationResult:
        """
        Confirm the CIN selected from the search results.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        company_name : str

        selected_cin : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KycVerificationResult
            Verification result

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.sub_account_kyc.confirm_subaccount_cin(
            sub_auth_id="SA_XXXXXX",
            company_name="ACME PRIVATE LIMITED",
            selected_cin="U72900KA2024PTC123456",
        )
        """
        _response = self._raw_client.confirm_subaccount_cin(
            sub_auth_id, company_name=company_name, selected_cin=selected_cin, request_options=request_options
        )
        return _response.data

    def subaccount_digilocker_initiate(
        self,
        sub_auth_id: str,
        *,
        redirect_url: str,
        oauth_state: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Returns the DigiLocker authorization link and an `access_request_id`.
        The customer completes the OAuth flow on the DigiLocker portal, after
        which you finalize with
        [DigiLocker verify](#operation/subaccount-digilocker-verify).

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        redirect_url : str

        oauth_state : typing.Optional[str]
            Opaque value echoed back on the redirect for CSRF protection.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            DigiLocker authorization link

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.sub_account_kyc.subaccount_digilocker_initiate(
            sub_auth_id="SA_XXXXXX",
            redirect_url="https://partner.example.com/kyc/callback",
        )
        """
        _response = self._raw_client.subaccount_digilocker_initiate(
            sub_auth_id, redirect_url=redirect_url, oauth_state=oauth_state, request_options=request_options
        )
        return _response.data

    def subaccount_digilocker_verify(
        self,
        sub_auth_id: str,
        *,
        access_request_id: str,
        linked_number: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> KycVerificationResult:
        """
        Finalize Aadhaar via DigiLocker after the customer completes OAuth.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        access_request_id : str

        linked_number : typing.Optional[str]
            Optional. Binds the Aadhaar to a specific number (92-series).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KycVerificationResult
            Verification result

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.sub_account_kyc.subaccount_digilocker_verify(
            sub_auth_id="SA_XXXXXX",
            access_request_id="AR_xxxxxxxx",
        )
        """
        _response = self._raw_client.subaccount_digilocker_verify(
            sub_auth_id,
            access_request_id=access_request_id,
            linked_number=linked_number,
            request_options=request_options,
        )
        return _response.data

    def create_subaccount_kyc_session(
        self,
        sub_auth_id: str,
        *,
        account_auth_id: str,
        flow_type: CreateSubaccountKycSessionRequestFlowType,
        customer_email: typing.Optional[str] = OMIT,
        redirect_url: typing.Optional[str] = OMIT,
        webhook_url: typing.Optional[str] = OMIT,
        expires_in_days: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Creates a Vobiz-hosted KYC session for the sub-account. With
        `flow_type=email` (default) Vobiz emails the customer a signed link
        (from `kyc@vobiz.ai`, hosted at `kyc.vobiz.ai`) and `customer_email` is
        required. With `flow_type=redirect`, omit `customer_email`, pass a
        `redirect_url`, and the `widget_url` is returned directly for an inline
        redirect.

        This is the sub-account–scoped equivalent of the partner-level
        [KYC Sessions](/partner/api/kyc-sessions) endpoint.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        account_auth_id : str
            The sub-account's auth_id (typically equal to the path `sub_auth_id`).

        flow_type : CreateSubaccountKycSessionRequestFlowType

        customer_email : typing.Optional[str]
            Required when `flow_type` is `email`.

        redirect_url : typing.Optional[str]
            Required when `flow_type` is `redirect`. After verification the customer's
            browser is sent to this URL.

        webhook_url : typing.Optional[str]
            HTTPS endpoint VoBiz POSTs the KYC result to. Omit it and no callbacks are sent.

        expires_in_days : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            KYC session created

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )
        client.sub_account_kyc.create_subaccount_kyc_session(
            sub_auth_id="SA_XXXXXX",
            account_auth_id="SA_XXXXXX",
            flow_type="email",
            customer_email="customer@example.com",
            webhook_url="https://your-app.example.com/kyc/webhook",
            expires_in_days=30,
        )
        """
        _response = self._raw_client.create_subaccount_kyc_session(
            sub_auth_id,
            account_auth_id=account_auth_id,
            flow_type=flow_type,
            customer_email=customer_email,
            redirect_url=redirect_url,
            webhook_url=webhook_url,
            expires_in_days=expires_in_days,
            request_options=request_options,
        )
        return _response.data


class AsyncSubAccountKycClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSubAccountKycClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSubAccountKycClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSubAccountKycClient
        """
        return self._raw_client

    async def get_subaccount_kyc_status(
        self, sub_auth_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> SubAccountKycStatus:
        """
        Returns the aggregated KYC state for a `customer_use` sub-account —
        which verifications have passed, whether calls are still blocked, and
        the business type. The caller must be the parent main account that owns
        the sub-account (or an admin).

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SubAccountKycStatus
            Aggregated KYC state

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.sub_account_kyc.get_subaccount_kyc_status(
                sub_auth_id="SA_XXXXXX",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_subaccount_kyc_status(sub_auth_id, request_options=request_options)
        return _response.data

    async def verify_subaccount_pan(
        self, sub_auth_id: str, *, pan: str, request_options: typing.Optional[RequestOptions] = None
    ) -> KycVerificationResult:
        """
        Runs a real PAN verification (Perfios) for the sub-account. `pan` must
        be exactly 10 characters. Persists a `kyc_verifications` row and
        recomputes the sub-account's aggregated `kyc_status`.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        pan : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KycVerificationResult
            Verification result

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.sub_account_kyc.verify_subaccount_pan(
                sub_auth_id="SA_XXXXXX",
                pan="ABCDE1234F",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.verify_subaccount_pan(sub_auth_id, pan=pan, request_options=request_options)
        return _response.data

    async def verify_subaccount_gst(
        self, sub_auth_id: str, *, gstin: str, request_options: typing.Optional[RequestOptions] = None
    ) -> KycVerificationResult:
        """
        Runs a real GSTIN verification. `gstin` must be a 15-character GSTIN.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        gstin : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KycVerificationResult
            Verification result

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.sub_account_kyc.verify_subaccount_gst(
                sub_auth_id="SA_XXXXXX",
                gstin="29AAJCN5983D1Z0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.verify_subaccount_gst(
            sub_auth_id, gstin=gstin, request_options=request_options
        )
        return _response.data

    async def search_subaccount_cin(
        self, sub_auth_id: str, *, company_name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Name-based CIN lookup. Returns candidate company matches; pick one and
        pass it to [CIN confirm](#operation/confirm-subaccount-cin).

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        company_name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Candidate matches

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.sub_account_kyc.search_subaccount_cin(
                sub_auth_id="SA_XXXXXX",
                company_name="ACME PRIVATE LIMITED",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search_subaccount_cin(
            sub_auth_id, company_name=company_name, request_options=request_options
        )
        return _response.data

    async def confirm_subaccount_cin(
        self,
        sub_auth_id: str,
        *,
        company_name: str,
        selected_cin: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> KycVerificationResult:
        """
        Confirm the CIN selected from the search results.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        company_name : str

        selected_cin : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KycVerificationResult
            Verification result

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.sub_account_kyc.confirm_subaccount_cin(
                sub_auth_id="SA_XXXXXX",
                company_name="ACME PRIVATE LIMITED",
                selected_cin="U72900KA2024PTC123456",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.confirm_subaccount_cin(
            sub_auth_id, company_name=company_name, selected_cin=selected_cin, request_options=request_options
        )
        return _response.data

    async def subaccount_digilocker_initiate(
        self,
        sub_auth_id: str,
        *,
        redirect_url: str,
        oauth_state: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Returns the DigiLocker authorization link and an `access_request_id`.
        The customer completes the OAuth flow on the DigiLocker portal, after
        which you finalize with
        [DigiLocker verify](#operation/subaccount-digilocker-verify).

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        redirect_url : str

        oauth_state : typing.Optional[str]
            Opaque value echoed back on the redirect for CSRF protection.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            DigiLocker authorization link

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.sub_account_kyc.subaccount_digilocker_initiate(
                sub_auth_id="SA_XXXXXX",
                redirect_url="https://partner.example.com/kyc/callback",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.subaccount_digilocker_initiate(
            sub_auth_id, redirect_url=redirect_url, oauth_state=oauth_state, request_options=request_options
        )
        return _response.data

    async def subaccount_digilocker_verify(
        self,
        sub_auth_id: str,
        *,
        access_request_id: str,
        linked_number: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> KycVerificationResult:
        """
        Finalize Aadhaar via DigiLocker after the customer completes OAuth.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        access_request_id : str

        linked_number : typing.Optional[str]
            Optional. Binds the Aadhaar to a specific number (92-series).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        KycVerificationResult
            Verification result

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.sub_account_kyc.subaccount_digilocker_verify(
                sub_auth_id="SA_XXXXXX",
                access_request_id="AR_xxxxxxxx",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.subaccount_digilocker_verify(
            sub_auth_id,
            access_request_id=access_request_id,
            linked_number=linked_number,
            request_options=request_options,
        )
        return _response.data

    async def create_subaccount_kyc_session(
        self,
        sub_auth_id: str,
        *,
        account_auth_id: str,
        flow_type: CreateSubaccountKycSessionRequestFlowType,
        customer_email: typing.Optional[str] = OMIT,
        redirect_url: typing.Optional[str] = OMIT,
        webhook_url: typing.Optional[str] = OMIT,
        expires_in_days: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Any:
        """
        Creates a Vobiz-hosted KYC session for the sub-account. With
        `flow_type=email` (default) Vobiz emails the customer a signed link
        (from `kyc@vobiz.ai`, hosted at `kyc.vobiz.ai`) and `customer_email` is
        required. With `flow_type=redirect`, omit `customer_email`, pass a
        `redirect_url`, and the `widget_url` is returned directly for an inline
        redirect.

        This is the sub-account–scoped equivalent of the partner-level
        [KYC Sessions](/partner/api/kyc-sessions) endpoint.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        account_auth_id : str
            The sub-account's auth_id (typically equal to the path `sub_auth_id`).

        flow_type : CreateSubaccountKycSessionRequestFlowType

        customer_email : typing.Optional[str]
            Required when `flow_type` is `email`.

        redirect_url : typing.Optional[str]
            Required when `flow_type` is `redirect`. After verification the customer's
            browser is sent to this URL.

        webhook_url : typing.Optional[str]
            HTTPS endpoint VoBiz POSTs the KYC result to. Omit it and no callbacks are sent.

        expires_in_days : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            KYC session created

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_id="YOUR_AUTH_ID",
            auth_token="YOUR_AUTH_TOKEN",
            username="YOUR_USERNAME",
            password="YOUR_PASSWORD",
        )


        async def main() -> None:
            await client.sub_account_kyc.create_subaccount_kyc_session(
                sub_auth_id="SA_XXXXXX",
                account_auth_id="SA_XXXXXX",
                flow_type="email",
                customer_email="customer@example.com",
                webhook_url="https://your-app.example.com/kyc/webhook",
                expires_in_days=30,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_subaccount_kyc_session(
            sub_auth_id,
            account_auth_id=account_auth_id,
            flow_type=flow_type,
            customer_email=customer_email,
            redirect_url=redirect_url,
            webhook_url=webhook_url,
            expires_in_days=expires_in_days,
            request_options=request_options,
        )
        return _response.data
