# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.kyc_verification_result import KycVerificationResult
from ..types.sub_account_kyc_status import SubAccountKycStatus
from .types.create_subaccount_kyc_session_request_flow_type import CreateSubaccountKycSessionRequestFlowType
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawSubAccountKycClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def get_subaccount_kyc_status(
        self, sub_auth_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SubAccountKycStatus]:
        """
        Returns the aggregated KYC state for a `customer_use` sub-account —
        which verifications have passed, whether calls are still blocked, and
        the business type. The caller must be the parent main account that owns
        the sub-account (or an admin).

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SubAccountKycStatus]
            Aggregated KYC state
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/{encode_path_param(sub_auth_id)}/kyc/status",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SubAccountKycStatus,
                    parse_obj_as(
                        type_=SubAccountKycStatus,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def verify_subaccount_pan(
        self, sub_auth_id: str, *, pan: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[KycVerificationResult]:
        """
        Runs a real PAN verification (Perfios) for the sub-account. `pan` must
        be exactly 10 characters. Persists a `kyc_verifications` row and
        recomputes the sub-account's aggregated `kyc_status`.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        pan : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[KycVerificationResult]
            Verification result
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/{encode_path_param(sub_auth_id)}/kyc/verify-pan",
            method="POST",
            json={
                "pan": pan,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def verify_subaccount_gst(
        self, sub_auth_id: str, *, gstin: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[KycVerificationResult]:
        """
        Runs a real GSTIN verification. `gstin` must be a 15-character GSTIN.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        gstin : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[KycVerificationResult]
            Verification result
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/{encode_path_param(sub_auth_id)}/kyc/verify-gst",
            method="POST",
            json={
                "gstin": gstin,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def search_subaccount_cin(
        self, sub_auth_id: str, *, company_name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Any]:
        """
        Name-based CIN lookup. Returns candidate company matches; pick one and
        pass it to [CIN confirm](#operation/confirm-subaccount-cin).

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        company_name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            Candidate matches
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/{encode_path_param(sub_auth_id)}/kyc/cin/search",
            method="POST",
            json={
                "company_name": company_name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def confirm_subaccount_cin(
        self,
        sub_auth_id: str,
        *,
        company_name: str,
        selected_cin: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[KycVerificationResult]:
        """
        Confirm the CIN selected from the search results.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        company_name : str

        selected_cin : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[KycVerificationResult]
            Verification result
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/{encode_path_param(sub_auth_id)}/kyc/cin/confirm",
            method="POST",
            json={
                "company_name": company_name,
                "selected_cin": selected_cin,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def subaccount_digilocker_initiate(
        self,
        sub_auth_id: str,
        *,
        redirect_url: str,
        oauth_state: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Any]:
        """
        Returns the DigiLocker authorization link and an `access_request_id`.
        The customer completes the OAuth flow on the DigiLocker portal, after
        which you finalize with
        [DigiLocker verify](#operation/subaccount-digilocker-verify).

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        redirect_url : str

        oauth_state : typing.Optional[str]
            Opaque value echoed back on the redirect for CSRF protection.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            DigiLocker authorization link
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/{encode_path_param(sub_auth_id)}/kyc/digilocker/initiate",
            method="POST",
            json={
                "redirect_url": redirect_url,
                "oauth_state": oauth_state,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def subaccount_digilocker_verify(
        self,
        sub_auth_id: str,
        *,
        access_request_id: str,
        linked_number: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[KycVerificationResult]:
        """
        Finalize Aadhaar via DigiLocker after the customer completes OAuth.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        access_request_id : str

        linked_number : typing.Optional[str]
            Optional. Binds the Aadhaar to a specific number (92-series).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[KycVerificationResult]
            Verification result
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/{encode_path_param(sub_auth_id)}/kyc/digilocker/verify",
            method="POST",
            json={
                "access_request_id": access_request_id,
                "linked_number": linked_number,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_subaccount_kyc_session(
        self,
        sub_auth_id: str,
        *,
        account_auth_id: str,
        flow_type: CreateSubaccountKycSessionRequestFlowType,
        customer_email: typing.Optional[str] = OMIT,
        redirect_url: typing.Optional[str] = OMIT,
        webhook_url: typing.Optional[str] = OMIT,
        expires_in_days: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[typing.Any]:
        """
        Creates a Vobiz-hosted KYC session for the sub-account. With
        `flow_type=email` (default) Vobiz emails the customer a signed link
        (from `kyc@vobiz.ai`, hosted at `kyc.vobiz.ai`) and `customer_email` is
        required. With `flow_type=redirect`, omit `customer_email`, pass a
        `redirect_url`, and the `widget_url` is returned directly for an inline
        redirect.

        This is the sub-account–scoped equivalent of the partner-level
        [KYC Sessions](/partner/api/kyc-sessions) endpoint.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        account_auth_id : str
            The sub-account's auth_id (typically equal to the path `sub_auth_id`).

        flow_type : CreateSubaccountKycSessionRequestFlowType

        customer_email : typing.Optional[str]
            Required when `flow_type` is `email`.

        redirect_url : typing.Optional[str]
            Required when `flow_type` is `redirect`. After verification the customer's
            browser is sent to this URL.

        webhook_url : typing.Optional[str]
            HTTPS endpoint VoBiz POSTs the KYC result to. Omit it and no callbacks are sent.

        expires_in_days : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Any]
            KYC session created
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/{encode_path_param(sub_auth_id)}/kyc-sessions",
            method="POST",
            json={
                "account_auth_id": account_auth_id,
                "flow_type": flow_type,
                "customer_email": customer_email,
                "redirect_url": redirect_url,
                "webhook_url": webhook_url,
                "expires_in_days": expires_in_days,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawSubAccountKycClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def get_subaccount_kyc_status(
        self, sub_auth_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SubAccountKycStatus]:
        """
        Returns the aggregated KYC state for a `customer_use` sub-account —
        which verifications have passed, whether calls are still blocked, and
        the business type. The caller must be the parent main account that owns
        the sub-account (or an admin).

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SubAccountKycStatus]
            Aggregated KYC state
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/{encode_path_param(sub_auth_id)}/kyc/status",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SubAccountKycStatus,
                    parse_obj_as(
                        type_=SubAccountKycStatus,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def verify_subaccount_pan(
        self, sub_auth_id: str, *, pan: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[KycVerificationResult]:
        """
        Runs a real PAN verification (Perfios) for the sub-account. `pan` must
        be exactly 10 characters. Persists a `kyc_verifications` row and
        recomputes the sub-account's aggregated `kyc_status`.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        pan : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[KycVerificationResult]
            Verification result
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/{encode_path_param(sub_auth_id)}/kyc/verify-pan",
            method="POST",
            json={
                "pan": pan,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def verify_subaccount_gst(
        self, sub_auth_id: str, *, gstin: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[KycVerificationResult]:
        """
        Runs a real GSTIN verification. `gstin` must be a 15-character GSTIN.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        gstin : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[KycVerificationResult]
            Verification result
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/{encode_path_param(sub_auth_id)}/kyc/verify-gst",
            method="POST",
            json={
                "gstin": gstin,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def search_subaccount_cin(
        self, sub_auth_id: str, *, company_name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Any]:
        """
        Name-based CIN lookup. Returns candidate company matches; pick one and
        pass it to [CIN confirm](#operation/confirm-subaccount-cin).

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        company_name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            Candidate matches
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/{encode_path_param(sub_auth_id)}/kyc/cin/search",
            method="POST",
            json={
                "company_name": company_name,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def confirm_subaccount_cin(
        self,
        sub_auth_id: str,
        *,
        company_name: str,
        selected_cin: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[KycVerificationResult]:
        """
        Confirm the CIN selected from the search results.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        company_name : str

        selected_cin : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[KycVerificationResult]
            Verification result
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/{encode_path_param(sub_auth_id)}/kyc/cin/confirm",
            method="POST",
            json={
                "company_name": company_name,
                "selected_cin": selected_cin,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def subaccount_digilocker_initiate(
        self,
        sub_auth_id: str,
        *,
        redirect_url: str,
        oauth_state: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Any]:
        """
        Returns the DigiLocker authorization link and an `access_request_id`.
        The customer completes the OAuth flow on the DigiLocker portal, after
        which you finalize with
        [DigiLocker verify](#operation/subaccount-digilocker-verify).

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        redirect_url : str

        oauth_state : typing.Optional[str]
            Opaque value echoed back on the redirect for CSRF protection.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            DigiLocker authorization link
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/{encode_path_param(sub_auth_id)}/kyc/digilocker/initiate",
            method="POST",
            json={
                "redirect_url": redirect_url,
                "oauth_state": oauth_state,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def subaccount_digilocker_verify(
        self,
        sub_auth_id: str,
        *,
        access_request_id: str,
        linked_number: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[KycVerificationResult]:
        """
        Finalize Aadhaar via DigiLocker after the customer completes OAuth.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        access_request_id : str

        linked_number : typing.Optional[str]
            Optional. Binds the Aadhaar to a specific number (92-series).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[KycVerificationResult]
            Verification result
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/{encode_path_param(sub_auth_id)}/kyc/digilocker/verify",
            method="POST",
            json={
                "access_request_id": access_request_id,
                "linked_number": linked_number,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    KycVerificationResult,
                    parse_obj_as(
                        type_=KycVerificationResult,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_subaccount_kyc_session(
        self,
        sub_auth_id: str,
        *,
        account_auth_id: str,
        flow_type: CreateSubaccountKycSessionRequestFlowType,
        customer_email: typing.Optional[str] = OMIT,
        redirect_url: typing.Optional[str] = OMIT,
        webhook_url: typing.Optional[str] = OMIT,
        expires_in_days: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[typing.Any]:
        """
        Creates a Vobiz-hosted KYC session for the sub-account. With
        `flow_type=email` (default) Vobiz emails the customer a signed link
        (from `kyc@vobiz.ai`, hosted at `kyc.vobiz.ai`) and `customer_email` is
        required. With `flow_type=redirect`, omit `customer_email`, pass a
        `redirect_url`, and the `widget_url` is returned directly for an inline
        redirect.

        This is the sub-account–scoped equivalent of the partner-level
        [KYC Sessions](/partner/api/kyc-sessions) endpoint.

        Parameters
        ----------
        sub_auth_id : str
            The sub-account's Auth ID.

        account_auth_id : str
            The sub-account's auth_id (typically equal to the path `sub_auth_id`).

        flow_type : CreateSubaccountKycSessionRequestFlowType

        customer_email : typing.Optional[str]
            Required when `flow_type` is `email`.

        redirect_url : typing.Optional[str]
            Required when `flow_type` is `redirect`. After verification the customer's
            browser is sent to this URL.

        webhook_url : typing.Optional[str]
            HTTPS endpoint VoBiz POSTs the KYC result to. Omit it and no callbacks are sent.

        expires_in_days : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Any]
            KYC session created
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sub-accounts/{encode_path_param(sub_auth_id)}/kyc-sessions",
            method="POST",
            json={
                "account_auth_id": account_auth_id,
                "flow_type": flow_type,
                "customer_email": customer_email,
                "redirect_url": redirect_url,
                "webhook_url": webhook_url,
                "expires_in_days": expires_in_days,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Any,
                    parse_obj_as(
                        type_=typing.Any,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
