# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawBalanceClient, RawBalanceClient
from .types.get_balance_response import GetBalanceResponse
from .types.list_transactions_response import ListTransactionsResponse


class BalanceClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBalanceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBalanceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBalanceClient
        """
        return self._raw_client

    def get_balance(
        self, auth_id: str, currency: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetBalanceResponse:
        """
        Retrieve the current account balance for a specific currency.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        currency : str
            Currency code (e.g. INR, USD)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetBalanceResponse
            Account balance

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.balance.get_balance(
            auth_id="MA_XXXXXX",
            currency="INR",
        )
        """
        _response = self._raw_client.get_balance(auth_id, currency, request_options=request_options)
        return _response.data

    def list_transactions(
        self,
        auth_id: str,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListTransactionsResponse:
        """
        Retrieve paginated transaction history for the account.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListTransactionsResponse
            Transaction list

        Examples
        --------
        from vobiz import Vobiz

        client = Vobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )
        client.balance.list_transactions(
            auth_id="MA_XXXXXX",
        )
        """
        _response = self._raw_client.list_transactions(
            auth_id, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data


class AsyncBalanceClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBalanceClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBalanceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBalanceClient
        """
        return self._raw_client

    async def get_balance(
        self, auth_id: str, currency: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetBalanceResponse:
        """
        Retrieve the current account balance for a specific currency.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        currency : str
            Currency code (e.g. INR, USD)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetBalanceResponse
            Account balance

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.balance.get_balance(
                auth_id="MA_XXXXXX",
                currency="INR",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_balance(auth_id, currency, request_options=request_options)
        return _response.data

    async def list_transactions(
        self,
        auth_id: str,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListTransactionsResponse:
        """
        Retrieve paginated transaction history for the account.

        Parameters
        ----------
        auth_id : str
            Your account Auth ID

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListTransactionsResponse
            Transaction list

        Examples
        --------
        import asyncio

        from vobiz import AsyncVobiz

        client = AsyncVobiz(
            auth_token="YOUR_AUTH_TOKEN",
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.balance.list_transactions(
                auth_id="MA_XXXXXX",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_transactions(
            auth_id, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data
