# This file was auto-generated by Fern from our API Definition.

import typing

ListCustomerTransactionsRequestTransactionType = typing.Union[
    typing.Literal["recharge", "debit", "refund", "transfer"], typing.Any
]
