# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_kyc_session_request_flow_type import CreateKycSessionRequestFlowType
    from .create_kyc_session_request_reminder_schedule_item import CreateKycSessionRequestReminderScheduleItem
    from .create_kyc_session_request_reminder_schedule_item_trigger import (
        CreateKycSessionRequestReminderScheduleItemTrigger,
    )
    from .get_partner_dashboard_response import GetPartnerDashboardResponse
    from .get_partner_dashboard_response_accounts import GetPartnerDashboardResponseAccounts
    from .get_partner_dashboard_response_accounts_customers_item import GetPartnerDashboardResponseAccountsCustomersItem
    from .get_partner_dashboard_response_by_product import GetPartnerDashboardResponseByProduct
    from .get_partner_dashboard_response_by_product_sip_trunking import GetPartnerDashboardResponseByProductSipTrunking
    from .get_partner_dashboard_response_by_product_voice_api import GetPartnerDashboardResponseByProductVoiceApi
    from .get_partner_dashboard_response_calls import GetPartnerDashboardResponseCalls
    from .get_partner_dashboard_response_partner import GetPartnerDashboardResponsePartner
    from .get_partner_dashboard_response_period import GetPartnerDashboardResponsePeriod
    from .get_partner_dashboard_response_time_series_item import GetPartnerDashboardResponseTimeSeriesItem
    from .get_partner_dashboard_response_time_series_item_inbound import (
        GetPartnerDashboardResponseTimeSeriesItemInbound,
    )
    from .get_partner_dashboard_response_time_series_item_outbound import (
        GetPartnerDashboardResponseTimeSeriesItemOutbound,
    )
    from .get_partner_dashboard_response_traffic import GetPartnerDashboardResponseTraffic
    from .get_partner_dashboard_response_traffic_inbound import GetPartnerDashboardResponseTrafficInbound
    from .get_partner_dashboard_response_traffic_outbound import GetPartnerDashboardResponseTrafficOutbound
    from .get_partner_profile_response import GetPartnerProfileResponse
    from .list_customer_accounts_response import ListCustomerAccountsResponse
    from .list_customer_accounts_response_accounts_item import ListCustomerAccountsResponseAccountsItem
    from .list_customer_accounts_response_accounts_item_pricing_tier import (
        ListCustomerAccountsResponseAccountsItemPricingTier,
    )
    from .list_customer_cdrs_request_call_direction import ListCustomerCdrsRequestCallDirection
    from .list_customer_cdrs_request_status import ListCustomerCdrsRequestStatus
    from .list_customer_cdrs_response import ListCustomerCdrsResponse
    from .list_customer_cdrs_response_pagination import ListCustomerCdrsResponsePagination
    from .list_customer_cdrs_response_summary import ListCustomerCdrsResponseSummary
    from .list_customer_numbers_response import ListCustomerNumbersResponse
    from .list_customer_transactions_request_transaction_type import ListCustomerTransactionsRequestTransactionType
    from .list_customer_transactions_response import ListCustomerTransactionsResponse
    from .list_customer_transactions_response_summary import ListCustomerTransactionsResponseSummary
    from .list_customer_transactions_response_summary_by_reference_type_item import (
        ListCustomerTransactionsResponseSummaryByReferenceTypeItem,
    )
    from .list_customer_transactions_response_transactions_item import ListCustomerTransactionsResponseTransactionsItem
    from .list_kyc_sessions_request_status import ListKycSessionsRequestStatus
    from .list_kyc_sessions_response import ListKycSessionsResponse
    from .list_kyc_sessions_response_sessions_item import ListKycSessionsResponseSessionsItem
    from .list_kyc_sessions_response_sessions_item_metadata import ListKycSessionsResponseSessionsItemMetadata
    from .list_kyc_sessions_response_sessions_item_metadata_customer_ref import (
        ListKycSessionsResponseSessionsItemMetadataCustomerRef,
    )
    from .list_kyc_sessions_response_sessions_item_reminder_schedule_item import (
        ListKycSessionsResponseSessionsItemReminderScheduleItem,
    )
    from .list_kyc_sessions_response_sessions_item_verified_data import ListKycSessionsResponseSessionsItemVerifiedData
    from .list_kyc_sessions_response_sessions_item_verified_data_aadhaar_dob import (
        ListKycSessionsResponseSessionsItemVerifiedDataAadhaarDob,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "CreateKycSessionRequestFlowType": ".create_kyc_session_request_flow_type",
    "CreateKycSessionRequestReminderScheduleItem": ".create_kyc_session_request_reminder_schedule_item",
    "CreateKycSessionRequestReminderScheduleItemTrigger": ".create_kyc_session_request_reminder_schedule_item_trigger",
    "GetPartnerDashboardResponse": ".get_partner_dashboard_response",
    "GetPartnerDashboardResponseAccounts": ".get_partner_dashboard_response_accounts",
    "GetPartnerDashboardResponseAccountsCustomersItem": ".get_partner_dashboard_response_accounts_customers_item",
    "GetPartnerDashboardResponseByProduct": ".get_partner_dashboard_response_by_product",
    "GetPartnerDashboardResponseByProductSipTrunking": ".get_partner_dashboard_response_by_product_sip_trunking",
    "GetPartnerDashboardResponseByProductVoiceApi": ".get_partner_dashboard_response_by_product_voice_api",
    "GetPartnerDashboardResponseCalls": ".get_partner_dashboard_response_calls",
    "GetPartnerDashboardResponsePartner": ".get_partner_dashboard_response_partner",
    "GetPartnerDashboardResponsePeriod": ".get_partner_dashboard_response_period",
    "GetPartnerDashboardResponseTimeSeriesItem": ".get_partner_dashboard_response_time_series_item",
    "GetPartnerDashboardResponseTimeSeriesItemInbound": ".get_partner_dashboard_response_time_series_item_inbound",
    "GetPartnerDashboardResponseTimeSeriesItemOutbound": ".get_partner_dashboard_response_time_series_item_outbound",
    "GetPartnerDashboardResponseTraffic": ".get_partner_dashboard_response_traffic",
    "GetPartnerDashboardResponseTrafficInbound": ".get_partner_dashboard_response_traffic_inbound",
    "GetPartnerDashboardResponseTrafficOutbound": ".get_partner_dashboard_response_traffic_outbound",
    "GetPartnerProfileResponse": ".get_partner_profile_response",
    "ListCustomerAccountsResponse": ".list_customer_accounts_response",
    "ListCustomerAccountsResponseAccountsItem": ".list_customer_accounts_response_accounts_item",
    "ListCustomerAccountsResponseAccountsItemPricingTier": ".list_customer_accounts_response_accounts_item_pricing_tier",
    "ListCustomerCdrsRequestCallDirection": ".list_customer_cdrs_request_call_direction",
    "ListCustomerCdrsRequestStatus": ".list_customer_cdrs_request_status",
    "ListCustomerCdrsResponse": ".list_customer_cdrs_response",
    "ListCustomerCdrsResponsePagination": ".list_customer_cdrs_response_pagination",
    "ListCustomerCdrsResponseSummary": ".list_customer_cdrs_response_summary",
    "ListCustomerNumbersResponse": ".list_customer_numbers_response",
    "ListCustomerTransactionsRequestTransactionType": ".list_customer_transactions_request_transaction_type",
    "ListCustomerTransactionsResponse": ".list_customer_transactions_response",
    "ListCustomerTransactionsResponseSummary": ".list_customer_transactions_response_summary",
    "ListCustomerTransactionsResponseSummaryByReferenceTypeItem": ".list_customer_transactions_response_summary_by_reference_type_item",
    "ListCustomerTransactionsResponseTransactionsItem": ".list_customer_transactions_response_transactions_item",
    "ListKycSessionsRequestStatus": ".list_kyc_sessions_request_status",
    "ListKycSessionsResponse": ".list_kyc_sessions_response",
    "ListKycSessionsResponseSessionsItem": ".list_kyc_sessions_response_sessions_item",
    "ListKycSessionsResponseSessionsItemMetadata": ".list_kyc_sessions_response_sessions_item_metadata",
    "ListKycSessionsResponseSessionsItemMetadataCustomerRef": ".list_kyc_sessions_response_sessions_item_metadata_customer_ref",
    "ListKycSessionsResponseSessionsItemReminderScheduleItem": ".list_kyc_sessions_response_sessions_item_reminder_schedule_item",
    "ListKycSessionsResponseSessionsItemVerifiedData": ".list_kyc_sessions_response_sessions_item_verified_data",
    "ListKycSessionsResponseSessionsItemVerifiedDataAadhaarDob": ".list_kyc_sessions_response_sessions_item_verified_data_aadhaar_dob",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateKycSessionRequestFlowType",
    "CreateKycSessionRequestReminderScheduleItem",
    "CreateKycSessionRequestReminderScheduleItemTrigger",
    "GetPartnerDashboardResponse",
    "GetPartnerDashboardResponseAccounts",
    "GetPartnerDashboardResponseAccountsCustomersItem",
    "GetPartnerDashboardResponseByProduct",
    "GetPartnerDashboardResponseByProductSipTrunking",
    "GetPartnerDashboardResponseByProductVoiceApi",
    "GetPartnerDashboardResponseCalls",
    "GetPartnerDashboardResponsePartner",
    "GetPartnerDashboardResponsePeriod",
    "GetPartnerDashboardResponseTimeSeriesItem",
    "GetPartnerDashboardResponseTimeSeriesItemInbound",
    "GetPartnerDashboardResponseTimeSeriesItemOutbound",
    "GetPartnerDashboardResponseTraffic",
    "GetPartnerDashboardResponseTrafficInbound",
    "GetPartnerDashboardResponseTrafficOutbound",
    "GetPartnerProfileResponse",
    "ListCustomerAccountsResponse",
    "ListCustomerAccountsResponseAccountsItem",
    "ListCustomerAccountsResponseAccountsItemPricingTier",
    "ListCustomerCdrsRequestCallDirection",
    "ListCustomerCdrsRequestStatus",
    "ListCustomerCdrsResponse",
    "ListCustomerCdrsResponsePagination",
    "ListCustomerCdrsResponseSummary",
    "ListCustomerNumbersResponse",
    "ListCustomerTransactionsRequestTransactionType",
    "ListCustomerTransactionsResponse",
    "ListCustomerTransactionsResponseSummary",
    "ListCustomerTransactionsResponseSummaryByReferenceTypeItem",
    "ListCustomerTransactionsResponseTransactionsItem",
    "ListKycSessionsRequestStatus",
    "ListKycSessionsResponse",
    "ListKycSessionsResponseSessionsItem",
    "ListKycSessionsResponseSessionsItemMetadata",
    "ListKycSessionsResponseSessionsItemMetadataCustomerRef",
    "ListKycSessionsResponseSessionsItemReminderScheduleItem",
    "ListKycSessionsResponseSessionsItemVerifiedData",
    "ListKycSessionsResponseSessionsItemVerifiedDataAadhaarDob",
]
