# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_partner_dashboard_response_traffic_inbound import GetPartnerDashboardResponseTrafficInbound
from .get_partner_dashboard_response_traffic_outbound import GetPartnerDashboardResponseTrafficOutbound


class GetPartnerDashboardResponseTraffic(UniversalBaseModel):
    inbound: GetPartnerDashboardResponseTrafficInbound
    outbound: GetPartnerDashboardResponseTrafficOutbound

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.forbid
