# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_partner_dashboard_response_accounts import GetPartnerDashboardResponseAccounts
from .get_partner_dashboard_response_by_product import GetPartnerDashboardResponseByProduct
from .get_partner_dashboard_response_calls import GetPartnerDashboardResponseCalls
from .get_partner_dashboard_response_partner import GetPartnerDashboardResponsePartner
from .get_partner_dashboard_response_period import GetPartnerDashboardResponsePeriod
from .get_partner_dashboard_response_time_series_item import GetPartnerDashboardResponseTimeSeriesItem
from .get_partner_dashboard_response_traffic import GetPartnerDashboardResponseTraffic


class GetPartnerDashboardResponse(UniversalBaseModel):
    partner: GetPartnerDashboardResponsePartner
    period: GetPartnerDashboardResponsePeriod
    accounts: GetPartnerDashboardResponseAccounts
    total_balance: str
    currency: str
    calls: GetPartnerDashboardResponseCalls
    traffic: GetPartnerDashboardResponseTraffic
    by_product: GetPartnerDashboardResponseByProduct
    time_series: typing.List[GetPartnerDashboardResponseTimeSeriesItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.forbid
