# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .list_kyc_sessions_response_sessions_item_metadata import ListKycSessionsResponseSessionsItemMetadata
from .list_kyc_sessions_response_sessions_item_reminder_schedule_item import (
    ListKycSessionsResponseSessionsItemReminderScheduleItem,
)
from .list_kyc_sessions_response_sessions_item_verified_data import ListKycSessionsResponseSessionsItemVerifiedData


class ListKycSessionsResponseSessionsItem(UniversalBaseModel):
    id: str
    account_auth_id: str
    customer_email: typing.Optional[str] = None
    kyc_type: typing.Optional[str] = None
    status: str
    expires_at: str
    first_opened_at: typing.Optional[str] = None
    completed_at: typing.Optional[str] = None
    webhook_url: typing.Optional[str] = None
    redirect_url: typing.Optional[str] = None
    reminder_schedule: typing.List[ListKycSessionsResponseSessionsItemReminderScheduleItem]
    metadata: ListKycSessionsResponseSessionsItemMetadata
    verified_data: ListKycSessionsResponseSessionsItemVerifiedData
    created_at: str
    updated_at: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.forbid
