# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ListKycSessionsResponseSessionsItemVerifiedDataAadhaarDob(UniversalBaseModel):
    pan_type: typing.Optional[str] = None
    pan_number: typing.Optional[str] = None
    pan_name_match: typing.Optional[bool] = None
    completed_steps: typing.Optional[typing.List[str]] = None
    pan_registered_name: typing.Optional[str] = None
    gender: typing.Optional[str] = None
    address: typing.Optional[str] = None
    aadhaar_dob: typing.Optional[str] = None
    aadhaar_name: typing.Optional[str] = None
    masked_aadhaar: typing.Optional[str] = None
    pan_name: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="forbid", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.forbid
